server/container/cassandra-guice/src/main/java/org/apache/james/jmap/JMAPCommonModule.java, server/container/cassandra-guice/src/main/java/org/apache/james/jmap/MethodsModule.java, server/protocols/jmap-integration-testing/src/test/java/org/apache/james/jmap/methods/SetMessagesMethodTest.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/exceptions/MailboxRoleNotFoundException.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/methods/MIMEMessageConverter.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/methods/MessageWithId.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/methods/SetMessagesCreationProcessor.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/methods/SetMessagesDestructionProcessor.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/methods/SetMessagesMethod.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/methods/SetMessagesProcessor.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/methods/SetMessagesUpdateProcessor.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/methods/ValidationResult.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/model/CreationMessage.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/model/CreationMessageId.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/model/SetMessagesRequest.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/model/SetMessagesResponse.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/send/MailFactory.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/methods/MIMEMessageConverterTest.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/methods/SetMessagesCreationProcessorTest.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/methods/SetMessagesUpdateProcessorTest.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/methods/UpdateMessagePatchConverterTest.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/model/CreationMessageTest.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/model/SetMessagesRequestTest.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/model/SetMessagesResponseTest.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/send/MailFactoryTest.java
Integration tests and documentation update are still missing
=> James 1692 final

server/protocols/jmap-integration-testing/src/test/java/org/apache/james/jmap/methods/GetMessageListMethodTest.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/methods/GetMessageListMethod.java
Before all the mailboxes of every users where sent.
Now filtering with a MailboxQuery.
=> JAMES-1696 getMessageList should only return current user mailboxes

README.txt
- add command for building james artifact (guice/cassandra section)
- add missing jmap port mapping when running james container.
- add some missing markdown formatting
=> update docker/guice section in README

server/protocols/jmap-integration-testing/src/test/java/org/apache/james/jmap/methods/SetMessagesMethodTest.java, server/protocols/jmap/doc/specs/spec/message.mdwn
recently added "setMessages - send a message" feature was missing some integration tests.
JMAP spec had not been updated in previous pull requests related to JAMES-1692 (apache jira) issue.
=> JAMES-1699 setMessages - send message feature - add tests

server/data/data-api/src/main/java/org/apache/james/user/api/AlreadyExistInUsersRepositoryException.java, server/data/data-library/src/main/java/org/apache/james/user/lib/AbstractUsersRepository.java, server/protocols/jmap/pom.xml, server/protocols/jmap/src/main/java/org/apache/james/jmap/FirstUserConnectionFilter.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/FirstUserConnectionFilterTest.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/FirstUserConnectionFilterThreadTest.java
Using thread-weaver to really test racing condition.
Manual mock seems to be necessary as Mockito and thread-weaver seem to conflict.
=> JAMES-1700 Don't fail in account creation if user already exists

mailbox/api/pom.xml, mailbox/memory/pom.xml, server/pom.xml, server/protocols/jmap-integration-testing/jmap-integration-testing-common/src/test/java/org/apache/james/jmap/methods/integration/SetMailboxesMethodTest.java, server/protocols/jmap/pom.xml, server/protocols/jmap/src/main/java/org/apache/james/jmap/exceptions/MailboxNameException.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/exceptions/MailboxParentNotFoundException.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/methods/GetMailboxesMethod.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/methods/SetMailboxesCreationProcessor.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/methods/SetMailboxesMethod.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/model/SetError.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/model/SetMailboxesResponse.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/model/mailbox/Mailbox.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/utils/CollectionHierarchySorter.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/utils/MailboxUtils.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/utils/SortingHierarchicalCollections.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/methods/GetMailboxesMethodTest.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/methods/SetMailboxesCreationProcessorTest.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/methods/SetMailboxesMethodTest.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/model/mailbox/MailboxTest.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/utils/CollectionHierarchySorterTest.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/utils/MailboxUtilsTest.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/utils/SortingHierarchicalCollectionsTest.java
Rebase #198 and take care of comments.
Two new tests added: 
- creating a mailbox that already exists
- cycle detection
=> James 1712 2

server/container/guice/cassandra-guice/pom.xml
=> JAMES-1739 depends on logback for cassandra-guice logging

dockerfiles/run/guice/Dockerfile, dockerfiles/run/guice/destination/conf/logback.xml, server/container/guice/cassandra-guice/src/main/resources/logback.xml
It should solve the "cassandra and ES are too verbose" problem.
=> James 1739

server/container/guice/guice-common/src/main/java/org/apache/james/jmap/JMAPCommonModule.java, server/protocols/jmap-integration-testing/jmap-integration-testing-common/src/test/java/org/apache/james/jmap/methods/integration/GetMessagesMethodTest.java, server/protocols/jmap/pom.xml, server/protocols/jmap/src/main/java/org/apache/james/jmap/methods/GetMessagesMethod.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/methods/SetMessagesCreationProcessor.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/model/Message.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/model/MessageFactory.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/model/MessagePreviewGenerator.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/methods/GetMessagesMethodTest.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/methods/SetMessagesCreationProcessorTest.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/model/MailboxMessageTest.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/model/MessagePreviewGeneratorTest.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/send/MailFactoryTest.java
James 1744 2  https://github.com/linagora/james-project/pull/266
=> James 1744 3 Preview should not contain HTML tags

mpt/impl/smtp/core/pom.xml, mpt/impl/smtp/core/src/main/java/org/apache/james/mpt/smtp/ForwardSmtpTest.java, mpt/pom.xml, server/container/util-java8/pom.xml, server/container/util-java8/src/test/java/org/apache/james/util/streams/SwarmGenericContainer.java, server/pom.xml, server/protocols/jmap-integration-testing/jmap-integration-testing-common/pom.xml
Only the last commit has to be reviewed.
The other is in review here: #281
=> James 1760 Add container affinity in docker based tests

backends-common/cassandra/src/main/java/org/apache/james/backends/cassandra/init/ClusterWithKeyspaceCreatedFactory.java, backends-common/cassandra/src/test/java/org/apache/james/backends/cassandra/CassandraCluster.java, server/container/guice/cassandra-guice/src/main/java/org/apache/james/modules/mailbox/CassandraSessionModule.java, server/container/guice/guice-common/src/main/java/org/apache/james/modules/server/CamelMailetContainerModule.java, server/container/jetty/src/main/java/org/apache/james/http/jetty/JettyHttpServer.java, server/pom.xml, server/protocols/protocols-library/src/main/java/org/apache/james/protocols/lib/netty/AbstractConfigurableAsyncServer.java
Make some tests a little faster
=> James 1772

mailet/base/src/main/java/org/apache/mailet/base/AutomaticallySentMailDetectorImpl.java, server/container/guice/memory-guice/src/main/java/org/apache/james/modules/server/MemoryMailQueueFactory.java, server/mailet/mailetcontainer-camel/src/main/java/org/apache/james/mailetcontainer/impl/JamesMailSpooler.java, server/protocols/jmap-integration-testing/jmap-integration-testing-common/src/test/java/org/apache/james/jmap/methods/integration/SetMessagesMethodTest.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/exceptions/AttachmentsNotFoundException.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/methods/MIMEMessageConverter.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/methods/SetMessagesCreationProcessor.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/model/Attachment.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/model/BlobId.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/model/CreationMessage.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/model/Message.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/model/MessageFactory.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/model/SetError.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/model/SetMessagesError.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/model/SubMessage.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/json/ParsingWritingObjects.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/methods/MIMEMessageConverterTest.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/methods/SetMessagesCreationProcessorTest.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/model/AttachmentTest.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/model/BlobIdTest.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/model/MailboxMessageTest.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/model/SetMessagesResponseTest.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/model/SubMailboxMessageTest.java, server/queue/queue-api/src/main/java/org/apache/james/queue/api/MailQueue.java
=> James 1790 - update SetMessage to support attachment with blobId

mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/model/impl/MessageParser.java, mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/impl/MessageParserTest.java, mailbox/store/src/test/resources/eml/oneHtmlAttachmentAndSomeTextInlined.eml, protocols/imap/src/main/java/org/apache/james/imap/processor/SetAnnotationProcessor.java, server/protocols/jmap-integration-testing/jmap-integration-testing-common/src/test/java/org/apache/james/jmap/methods/integration/SetMessagesMethodTest.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/methods/MIMEMessageConverter.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/methods/MIMEMessageConverterTest.java
=> James 1794: handle multipart/alternative

mailet/base/src/test/java/org/apache/mailet/base/test/FakeMail.java, mailet/standard/src/test/java/org/apache/james/transport/matchers/AllTest.java
CI for https://github.com/apache/james-project/pull/57
=> Mailet 111 CI testing

mailbox/elasticsearch/src/test/java/org/apache/james/mailbox/elasticsearch/ElasticSearchIntegrationTest.java, mailbox/lucene/src/test/java/org/apache/james/mailbox/lucene/search/LuceneMessageSearchIndexTest.java, mailbox/memory/src/test/java/org/apache/james/mailbox/inmemory/InMemoryMailboxManagerTest.java, mailbox/memory/src/test/java/org/apache/james/mailbox/inmemory/manager/InMemoryIntegrationResources.java, mailbox/scanning-search/src/test/java/org/apache/james/mailbox/store/search/SimpleMessageSearchIndexTest.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/FakeAuthenticator.java, mailbox/store/src/test/java/org/apache/james/mailbox/store/StoreMailboxManagerTest.java, mpt/impl/imap-mailbox/cassandra/src/test/java/org/apache/james/mpt/imapmailbox/cassandra/host/CassandraHostSystem.java, mpt/impl/imap-mailbox/elasticsearch/src/test/java/org/apache/james/mpt/imapmailbox/elasticsearch/host/ElasticSearchHostSystem.java, mpt/impl/imap-mailbox/hbase/src/test/java/org/apache/james/mpt/imapmailbox/hbase/host/HBaseHostSystem.java, mpt/impl/imap-mailbox/inmemory/src/test/java/org/apache/james/mpt/imapmailbox/inmemory/host/InMemoryEventAsynchronousHostSystem.java, mpt/impl/imap-mailbox/inmemory/src/test/java/org/apache/james/mpt/imapmailbox/inmemory/host/InMemoryHostSystem.java, mpt/impl/imap-mailbox/jcr/src/test/java/org/apache/james/mpt/imapmailbox/jcr/host/JCRHostSystem.java, mpt/impl/imap-mailbox/jpa/src/test/java/org/apache/james/mpt/imapmailbox/jpa/host/JPAHostSystem.java, mpt/impl/imap-mailbox/maildir/src/test/java/org/apache/james/mpt/imapmailbox/maildir/host/MaildirHostSystem.java, server/container/mailbox-adapter/src/test/java/org/apache/james/adapter/mailbox/MailboxManagementTest.java, server/protocols/jmap/pom.xml, server/protocols/jmap/src/test/java/org/apache/james/jmap/FirstUserConnectionFilterThreadTest.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/methods/GetMailboxesMethodTest.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/methods/GetMessagesMethodTest.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/methods/SetMessagesCreationProcessorTest.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/model/MailboxFactoryTest.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/send/MailFactoryTest.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/send/PostDequeueDecoratorTest.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/utils/MailboxUtilsTest.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/utils/SortToComparatorConvertorTest.java
Don't worry, only the last commit is to review in this PR
=> James 1818 Remove store imports in test classes

mailbox/caching/src/main/java/org/apache/james/mailbox/caching/CachingMailboxSessionMapperFactory.java, mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/CassandraMailboxSessionMapperFactory.java, mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraAnnotationMapper.java, mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraMapperProvider.java, mailbox/hbase/src/main/java/org/apache/james/mailbox/hbase/HBaseMailboxSessionMapperFactory.java, mailbox/jcr/src/main/java/org/apache/james/mailbox/jcr/JCRMailboxSessionMapperFactory.java, mailbox/jpa/src/main/java/org/apache/james/mailbox/jpa/JPAMailboxSessionMapperFactory.java, mailbox/maildir/src/main/java/org/apache/james/mailbox/maildir/MaildirMailboxSessionMapperFactory.java, mailbox/memory/src/main/java/org/apache/james/mailbox/inmemory/InMemoryMailboxSessionMapperFactory.java, mailbox/memory/src/main/java/org/apache/james/mailbox/inmemory/mail/InMemoryAnnotationMapper.java, mailbox/memory/src/test/java/org/apache/james/mailbox/inmemory/mail/InMemoryMapperProvider.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/MailboxSessionMapperFactory.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMailboxManager.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/AnnotationMapper.java, mailbox/store/src/test/java/org/apache/james/mailbox/store/StoreMailboxManagerAnnotationTest.java, mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/AnnotationMapperTest.java
- Old behaviour: delete mailbox should delete all related annotations
- Issue with multiple annotations on mailbox: the annotation mapper must be unique on mapper factory
=> Mailbox 270: old behaviour and issue when insert multi annotation on mailbox

mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMailboxManager.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/event/MailboxAnnotationListener.java, mailbox/store/src/test/java/org/apache/james/mailbox/store/StoreMailboxManagerAnnotationTest.java, mailbox/store/src/test/java/org/apache/james/mailbox/store/event/MailboxAnnotationListenerTest.java, mpt/impl/imap-mailbox/core/src/main/resources/org/apache/james/imap/scripts/Annotation.test
For now, just saw the delete mailbox should be side effect.
- All the mailbox's annotation should be deleted when mailbox is deleted
=> Mailbox 270: old behaviour

mailbox/store/src/test/java/org/apache/james/mailbox/store/event/MailboxListenerRegistryTest.java
Here is my implementation for JAMES-1823, based on the findings and work of https://github.com/leepaul21 he did on this pull request : https://github.com/apache/james-project/pull/63
=> James 1823

james3-roadmap-progress/index.html, james3-roadmap-progress/progress.json
It's just a squash version of https://github.com/linagora/james-project/pull/418
=> JAMES-1845 Display James 3.0 release progress as an html

README.adoc
build step attempt to build images defined in the docker-compose file, it do not stand for "go, search, and install it from the internet for me"
=> JAMES-1834 Modifying instructions to retrieve images with docker-compose

mailet/mailetdocs-maven-plugin/pom.xml, mailet/mailetdocs-maven-plugin/src/main/java/org/apache/james/mailet/AbstractMailetdocsReport.java, mailet/mailetdocs-maven-plugin/src/main/java/org/apache/james/mailet/AggregateMailetdocsReport.java, mailet/mailetdocs-maven-plugin/src/main/java/org/apache/james/mailet/DefaultDescriptorsExtractor.java, mailet/mailetdocs-maven-plugin/src/main/java/org/apache/james/mailet/MailetdocsReport.java, mailet/pom.xml, mailet/src/site/xdoc/mailetdocs-maven-plugin/index.xml, pom.xml
#390 without plugin execution in Java 6 compilation
=> MAILET-123 Mailet documentation generation fails

mailbox/pom.xml, mailet/pom.xml, pom.xml, protocols/pom.xml, server/pom.xml, server/src/site/xdoc/release-notes.xml, src/site/xdoc/download.xml
Remains : uploading artifacts, releasing 3.0-beta5 on maven
I will PR again for uploads (1 day delay)
=> James 1830 Release 3.0-beta5

src/site/xdoc/download.xml, src/site/xdoc/index.xml, src/site/xdoc/newsarchive.xml
=> Website changes for 3.0.0-beta5

README.adoc
=> James 1830 3 Modify Readme after 3.0.0-beta5

README.adoc, dockerfiles/run/spring/provisioned/Dockerfile, dockerfiles/run/spring/provisioned/initialdata.sh, dockerfiles/run/spring/provisioned/startup.sh
It depends on JAMES-1842: JPA and Lucene should be default configuration
=> James 1857: JWS-Create James Image for get started part

server/protocols/protocols-smtp/src/main/java/org/apache/james/smtpserver/fastfail/JDBCGreylistHandler.java
https://github.com/apache/james-project/pull/65 
Based on the pull request opened by https://github.com/luo877280
=> JAMES-1865 Remove Spring ambiguous setWhiteListedNetworks

mailbox/caching/src/main/java/org/apache/james/mailbox/caching/CachingMailboxSessionMapperFactory.java, mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/CassandraMailboxSessionMapperFactory.java, mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraModSeqProvider.java, mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraUidProvider.java, mailbox/hbase/src/main/java/org/apache/james/mailbox/hbase/HBaseMailboxSessionMapperFactory.java, mailbox/hbase/src/main/java/org/apache/james/mailbox/hbase/mail/HBaseModSeqProvider.java, mailbox/hbase/src/main/java/org/apache/james/mailbox/hbase/mail/HBaseUidProvider.java, mailbox/jcr/src/main/java/org/apache/james/mailbox/jcr/JCRMailboxSessionMapperFactory.java, mailbox/jpa/src/main/java/org/apache/james/mailbox/jpa/JPAMailboxSessionMapperFactory.java, mailbox/maildir/src/main/java/org/apache/james/mailbox/maildir/MaildirMailboxSessionMapperFactory.java, mailbox/maildir/src/main/java/org/apache/james/mailbox/maildir/MaildirStore.java, mailbox/memory/src/main/java/org/apache/james/mailbox/inmemory/InMemoryMailboxSessionMapperFactory.java, mailbox/memory/src/main/java/org/apache/james/mailbox/inmemory/mail/InMemoryModSeqProvider.java, mailbox/memory/src/main/java/org/apache/james/mailbox/inmemory/mail/InMemoryUidProvider.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/MailboxSessionMapperFactory.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMessageIdManager.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/AbstractLockingModSeqProvider.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/AbstractLockingUidProvider.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/ModSeqProvider.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/UidProvider.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/quota/QuotaChecker.java, mailbox/store/src/test/java/org/apache/james/mailbox/store/AbstractMessageIdManagerSideEffectTest.java, mailbox/store/src/test/java/org/apache/james/mailbox/store/AbstractMessageIdManagerStorageTest.java, mailbox/store/src/test/java/org/apache/james/mailbox/store/MessageIdManagerTestSystem.java, mailbox/store/src/test/java/org/apache/james/mailbox/store/StoreMessageIdManagerSideEffectTest.java, mailbox/store/src/test/java/org/apache/james/mailbox/store/StoreMessageIdManagerTestSystem.java, mailbox/store/src/test/java/org/apache/james/mailbox/store/TestMailboxSessionMapperFactory.java, mailbox/zoo-seq-provider/src/main/java/org/apache/james/mailbox/store/mail/ZooUidProvider.java
Take the work of https://github.com/linagora/james-project/pull/484 and make it pass the "event" part of the messageIdManagerTests.
=> Unique id abstract message id manager

mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/CassandraMailboxManager.java, mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageDAO.java, mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageIdDAO.java, mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageIdMapper.java, mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/CassandraMessageIdManagerSideEffectTest.java, mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/CassandraMessageIdManagerStorageTest.java, mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/CassandraMessageIdManagerTestSystem.java, mailbox/maildir/src/main/resources/META-INF/spring/mailbox-maildir.xml, mailbox/memory/src/main/java/org/apache/james/mailbox/inmemory/InMemoryMailboxManager.java, mailbox/memory/src/main/resources/META-INF/spring/mailbox-memory.xml, mailbox/spring/src/test/resources/META-INF/spring/event-alias.xml, mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMailboxManager.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMessageIdManager.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/event/DefaultDelegatingMailboxListener.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/event/MailboxEventDispatcher.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/model/impl/SimpleMailboxMessage.java, mailbox/store/src/test/java/org/apache/james/mailbox/store/AbstractMessageIdManagerSideEffectTest.java, mailbox/store/src/test/java/org/apache/james/mailbox/store/AbstractMessageIdManagerStorageTest.java, mailbox/store/src/test/java/org/apache/james/mailbox/store/MailboxEventDispatcherTest.java, server/container/guice/cassandra-guice/src/main/java/org/apache/james/modules/mailbox/CassandraMailboxModule.java, server/container/guice/cassandra-guice/src/test/java/org/apache/james/CassandraJmapTestRule.java, server/container/guice/cassandra-guice/src/test/java/org/apache/james/CassandraMessageIdManagerInjectionTest.java, server/container/guice/guice-common/src/main/java/org/apache/james/modules/mailbox/DefaultEventModule.java, server/container/guice/memory-guice/src/main/java/org/apache/james/modules/mailbox/MemoryMailboxModule.java, server/container/spring/src/main/resources/META-INF/org/apache/james/spring-server.xml
Review only commits named JAMES-1888
Fixes : 
- Messages should be able to live in several mailboxes
- Do not return messages when mailbox do not exist
- Guice injection
- other small corrections
- Manager for MessageId tests
Security will be handled in an other ticket
=> James 1888 Tests for MessageIdManager

mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageIdMapper.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/FlagsUpdateCalculator.java, mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/MessageIdMapperTest.java, server/protocols/jmap-integration-testing/cassandra-jmap-integration-testing/src/test/java/org/apache/james/jmap/cassandra/CassandraGetMailboxesMethodTest.java, server/protocols/jmap-integration-testing/cassandra-jmap-integration-testing/src/test/java/org/apache/james/jmap/cassandra/CassandraGetMessageListMethodTest.java, server/protocols/jmap-integration-testing/cassandra-jmap-integration-testing/src/test/java/org/apache/james/jmap/cassandra/CassandraGetVacationResponseTest.java, server/protocols/jmap-integration-testing/cassandra-jmap-integration-testing/src/test/java/org/apache/james/jmap/cassandra/CassandraJmapAuthenticationTest.java, server/protocols/jmap-integration-testing/cassandra-jmap-integration-testing/src/test/java/org/apache/james/jmap/cassandra/CassandraSetMailboxesMethodTest.java, server/protocols/jmap-integration-testing/cassandra-jmap-integration-testing/src/test/java/org/apache/james/jmap/cassandra/CassandraSetMessagesMethodTest.java, server/protocols/jmap-integration-testing/cassandra-jmap-integration-testing/src/test/java/org/apache/james/jmap/cassandra/CassandraSetVacationResponseTest.java, server/protocols/jmap-integration-testing/cassandra-jmap-integration-testing/src/test/java/org/apache/james/jmap/cassandra/CassandraVacationIntegrationTest.java, server/protocols/jmap-integration-testing/cassandra-jmap-integration-testing/src/test/java/org/apache/james/jmap/cassandra/cucumber/CassandraDownloadCucumberTest.java, server/protocols/jmap-integration-testing/cassandra-jmap-integration-testing/src/test/java/org/apache/james/jmap/cassandra/cucumber/CassandraGetMessagesMethodTest.java, server/protocols/jmap-integration-testing/cassandra-jmap-integration-testing/src/test/java/org/apache/james/jmap/cassandra/cucumber/CassandraSetMailboxesMethodCucumberTest.java, server/protocols/jmap-integration-testing/cassandra-jmap-integration-testing/src/test/java/org/apache/james/jmap/cassandra/cucumber/CassandraStepdefs.java, server/protocols/jmap-integration-testing/cassandra-jmap-integration-testing/src/test/java/org/apache/james/jmap/cassandra/cucumber/CassandraUploadCucumberTest.java, server/protocols/jmap-integration-testing/jmap-integration-testing-common/src/test/java/org/apache/james/jmap/methods/integration/cucumber/GetMessagesMethodStepdefs.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/json/ObjectMapperFactory.java
#522 + two commits:
- c2d50bd: fix Cassandra JMAP integration tests
- c16f106: take care of comments
This PR is based on _unique-id-jmap branch_, so it may be merged via **GitHub**.
Then the final merge _linagora/unique-id-jmap_ to _apache/master_ should be done as regular merges.
=> JAMES-1892: Cassandra should Pass JMAP integration tests

mailbox/api/src/main/java/org/apache/james/mailbox/MailboxManager.java, mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/CassandraMailboxManager.java, mailbox/memory/src/main/java/org/apache/james/mailbox/inmemory/InMemoryMailboxManager.java, server/container/guice/cassandra-guice/src/test/java/org/apache/james/CassandraJamesServerTest.java, server/container/guice/cassandra-guice/src/test/java/org/apache/james/JamesCapabilitiesServerTest.java, server/container/guice/guice-common/src/main/java/org/apache/james/jmap/JMAPModule.java
- JMAP should check the capability
- Memory and Cassandra implements the capability
=> JAMES-1893 Add Unique_ID Message Capability in MailboxManager

mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageMapper.java, server/protocols/jmap-integration-testing/jmap-integration-testing-common/src/test/java/org/apache/james/jmap/methods/integration/SetMessagesMethodTest.java
This PR is for fixing a compilation bug with Java8 in eclipse 4.6.2
=> JAMES-1907 fix issue with eclipse 4.6.2

mailet/base/pom.xml, mailet/base/src/test/java/org/apache/mailet/base/test/MailUtil.java, mailet/base/src/test/java/org/apache/mailet/base/test/MimeMessageBuilder.java, mailet/standard/src/main/java/org/apache/james/transport/matchers/GenericRegexMatcher.java, mailet/standard/src/test/java/org/apache/james/transport/mailets/AddSubjectPrefixTest.java, mailet/standard/src/test/java/org/apache/james/transport/mailets/MailAttributesToMimeHeadersTest.java, mailet/standard/src/test/java/org/apache/james/transport/mailets/RemoveMimeHeaderTest.java, mailet/standard/src/test/java/org/apache/james/transport/mailets/StripAttachmentTest.java, mailet/standard/src/test/java/org/apache/james/transport/mailets/UnwrapTextTest.java, mailet/standard/src/test/java/org/apache/james/transport/matchers/NESSpamCheckTest.java, server/mailet/mailets/src/test/java/org/apache/james/transport/mailets/BounceTest.java, server/mailet/mailets/src/test/java/org/apache/james/transport/mailets/delivery/LocalDeliveryTest.java, server/mailet/mailets/src/test/java/org/apache/james/transport/mailets/delivery/MailDispatcherTest.java, server/mailet/mailets/src/test/java/org/apache/james/transport/mailets/delivery/MailboxAppenderTest.java, server/mailet/mailets/src/test/java/org/apache/james/transport/mailets/delivery/SieveIntegrationTest.java, server/mailet/mailets/src/test/java/org/apache/james/transport/mailets/delivery/SimpleMailStoreTest.java, server/mailet/mailets/src/test/java/org/apache/james/transport/mailets/delivery/ToRecipientFolderTest.java, server/mailet/mailets/src/test/java/org/apache/james/transport/mailets/managesieve/ManageSieveMailetTestCase.java
Take comment from: https://github.com/linagora/james-project/pull/537
=> MAILET-145: Improve readability of tests involving mime messages

backends-common/jpa/pom.xml, backends-common/jpa/src/test/java/org/apache/james/backends/jpa/JpaTestCluster.java, backends-common/pom.xml, mailbox/jpa/pom.xml, mailbox/jpa/src/test/java/org/apache/james/mailbox/jpa/JPAMailboxFixture.java, mailbox/jpa/src/test/java/org/apache/james/mailbox/jpa/JPAMailboxManagerTest.java, mailbox/jpa/src/test/java/org/apache/james/mailbox/jpa/JPASubscriptionManagerTest.java, mailbox/jpa/src/test/java/org/apache/james/mailbox/jpa/mail/JPAMapperProvider.java, mailbox/pom.xml, mailbox/tool/pom.xml, mpt/app/dependency-reduced-pom.xml, mpt/impl/imap-mailbox/jpa/pom.xml, mpt/impl/imap-mailbox/jpa/src/test/java/org/apache/james/mpt/imapmailbox/jpa/host/JPAHostSystem.java, mpt/impl/imap-mailbox/lucenesearch/pom.xml, mpt/impl/imap-mailbox/lucenesearch/src/test/java/org/apache/james/mpt/imapmailbox/lucenesearch/host/LuceneSearchHostSystem.java, mpt/pom.xml, server/container/guice/jpa-guice/pom.xml, server/container/spring/pom.xml, server/data/data-jpa/pom.xml, server/data/data-jpa/src/main/java/org/apache/james/rrt/jpa/model/JPARecipientRewrite.java, server/data/data-jpa/src/test/java/org/apache/james/domainlist/jpa/JPADomainListTest.java, server/data/data-jpa/src/test/java/org/apache/james/rrt/jpa/JPARecipientRewriteTableTest.java, server/data/data-jpa/src/test/java/org/apache/james/rrt/jpa/JPAStepdefs.java, server/pom.xml
Easy win for JPA information duplication...
=> PVN-10 Factorize mailbox EntityManagerFactory creation (JPA)

mailet/icalendar/pom.xml, mailet/pom.xml
To avoid us many small conflicts
Create your mailets under package org.apache.james.transport.mailets (so that it can be added in conf without FQDN)
=> MAILET-145 Introduce icalendar project

server/protocols/jmap-integration-testing/jmap-integration-testing-common/src/test/java/org/apache/james/jmap/methods/integration/cucumber/GetMessagesMethodStepdefs.java, server/protocols/jmap-integration-testing/jmap-integration-testing-common/src/test/resources/cucumber/GetMessages.feature, server/protocols/jmap-integration-testing/jmap-integration-testing-common/src/test/resources/eml/embeddedMultipartWithInlineTextAttachment.eml, server/protocols/jmap-integration-testing/jmap-integration-testing-common/src/test/resources/eml/textInMainMultipartHtmlInInnerMultipart.eml, server/protocols/jmap/src/main/java/org/apache/james/jmap/model/MessageContentExtractor.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/model/MessageContentExtractorTest.java
=> James 1913 1916 Fix some issues with David's emails

README.adoc
Nothing fancy, just make the README look a bit better.
=> Improve formatting and section structure

server/protocols/jmap-integration-testing/jmap-integration-testing-common/src/test/java/org/apache/james/jmap/methods/integration/SetMessagesMethodTest.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/methods/SetMessagesCreationProcessor.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/model/mailbox/Role.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/utils/SystemMailboxesProvider.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/utils/SystemMailboxesProviderImpl.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/methods/SetMessagesCreationProcessorTest.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/send/PostDequeueDecoratorTest.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/utils/SystemMailboxesProviderImplTest.java
=> James 1935 Optimize SetMessagesCreatorProcessor by reduce getMailboxes method

mailbox/hbase/src/main/java/org/apache/james/mailbox/hbase/mail/model/HBaseMailbox.java, mailbox/jcr/src/main/java/org/apache/james/mailbox/jcr/mail/model/JCRMailbox.java, mailbox/jpa/src/main/java/org/apache/james/mailbox/jpa/mail/model/JPAMailbox.java, mailbox/lucene/src/test/java/org/apache/james/mailbox/lucene/search/LuceneMailboxMessageSearchIndexTest.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMailboxManager.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/model/Mailbox.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/model/MailboxUtil.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/model/impl/SimpleMailbox.java, mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/ListMailboxAssertTest.java
=> JAMES-1935 search should be wider in order to prevent further DB reads

backends-common/cassandra/src/main/java/org/apache/james/backends/cassandra/components/CassandraTable.java, mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/CassandraMailboxSessionMapperFactory.java, mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraFirstUnseenDAO.java, mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraIndexTableHandler.java, mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageMapper.java, mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/modules/CassandraFirstUnseenModule.java, mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/table/CassandraFirstUnseenTable.java, mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/CassandraMailboxManagerTest.java, mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/CassandraSubscriptionManagerTest.java, mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/CassandraTestSystemFixture.java, mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraFirstUnseenDAOTest.java, mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraIndexTableHandlerTest.java, mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraMailboxManagerAttachmentTest.java, mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraMapperProvider.java, mpt/impl/imap-mailbox/cassandra/src/test/java/org/apache/james/mpt/imapmailbox/cassandra/host/CassandraHostSystem.java, server/container/guice/cassandra-guice/src/main/java/org/apache/james/modules/mailbox/CassandraMailboxModule.java
=> James 1945 Index table for finding first UNSEEN message in a mailbox

mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/CassandraMailboxSessionMapperFactory.java, mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraDeletedMessageDAO.java, mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraIndexTableHandler.java, mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageMapper.java, mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/modules/CassandraDeletedMessageModule.java, mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/table/CassandraDeletedMessageTable.java, mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/CassandraMailboxManagerTest.java, mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/CassandraSubscriptionManagerTest.java, mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/CassandraTestSystemFixture.java, mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraDeletedMessageDAOTest.java, mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraIndexTableHandlerTest.java, mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraMailboxManagerAttachmentTest.java, mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraMapperProvider.java, mailbox/pom.xml, mailet/pom.xml, mpt/impl/imap-mailbox/cassandra/src/test/java/org/apache/james/mpt/imapmailbox/cassandra/host/CassandraHostSystem.java, server/container/guice/cassandra-guice/src/main/java/org/apache/james/modules/mailbox/CassandraMailboxModule.java, server/container/util-java8/src/main/java/org/apache/james/util/CompletableFutureUtil.java, server/container/util-java8/src/main/java/org/apache/james/util/FluentFutureStream.java, server/container/util-java8/src/test/java/org/apache/james/util/CompletableFutureUtilTest.java
=> James 1948 better manage expunge

server/protocols/jmap/src/main/java/org/apache/james/jmap/methods/GetMessageListMethod.java
We were recording time after ES call...
=> JAMES-1950 Actually record time correctly in GetMessageList JMAP method

server/protocols/jmap-integration-testing/jmap-integration-testing-common/src/test/java/org/apache/james/jmap/ContainerTest.java
=> JAMES-1971 Improve ContainerTest by not binding an host address

src/site/xdoc/server/install.xml, src/site/xdoc/server/quick-start-cassandra.xml, src/site/xdoc/server/quick-start.xml
https://rawgit.com/chibenwa/james-project/JAMES-1992-show/site/server/install.html
https://rawgit.com/chibenwa/james-project/JAMES-1992-show/site/server/quick-start.html
Note please that all links points to a release, and not to master, in order to comply with release policy.
=> JAMES-1992 Consolidate getting started instructions

src/homepage/index.html
=> JAMES-2016 Add mentions for chat on the website

README.adoc
=> JAMES-2016 Add gitter badge on Github

mailbox/elasticsearch/src/main/java/org/apache/james/mailbox/elasticsearch/json/HeaderCollection.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/search/MessageSearches.java, mailet/standard/src/main/java/org/apache/james/transport/matchers/HasHeader.java, mailet/standard/src/test/java/org/apache/james/transport/matchers/HasHeaderTest.java, mailet/standard/src/test/resources/mime/headerFolded.mime, server/mailet/mailets/src/test/java/org/apache/james/transport/mailets/delivery/SieveIntegrationTest.java, server/mailet/mailets/src/test/resources/eml/gmail.eml, server/mailet/mailets/src/test/resources/org/apache/james/transport/mailets/delivery/headerEncodedFolded.script, server/pom.xml, server/protocols/jmap/src/main/java/org/apache/james/jmap/model/MessageFactory.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/model/MessageFactoryTest.java
Problem found with : 
- InMemory indexing
- JMAP raw headers
- JSieve
- HasHeader matcher
Needs https://github.com/linagora/james-jsieve/pull/9
Provides unit tests for https://github.com/linagora/james-jsieve/pull/9
=> JAMES-1900 Decode issues with headers

src/homepage/_posts/2017-05-16-mime4j-0.8.1.markdown
=> JAMES-2061 Add a post for mime4j 0.8.1

protocols/pom.xml
This was generating claspath clash for OpenPaaS mailet.
=> JAMES-2068 Update JSIEVE dependency in protocols

metrics/metrics-dropwizard/src/main/java/org/apache/james/metrics/dropwizard/DropWizardMetricFactory.java
=> JAMES-2084 Start JMX reporter on Spring

mailbox/store/src/main/java/org/apache/james/mailbox/store/probe/MailboxProbe.java, server/container/cli/src/main/java/org/apache/james/cli/ServerCmd.java, server/container/cli/src/main/java/org/apache/james/cli/probe/impl/JmxMailboxProbe.java, server/container/cli/src/main/java/org/apache/james/cli/type/CmdType.java, server/container/cli/src/test/java/org/apache/james/cli/ServerCmdTest.java, server/container/cli/src/test/java/org/apache/james/cli/type/CmdTypeTest.java, server/container/guice/mailbox/src/main/java/org/apache/james/modules/MailboxProbeImpl.java, server/container/mailbox-adapter/src/main/java/org/apache/james/adapter/mailbox/MailboxManagerManagement.java, server/container/mailbox-adapter/src/main/java/org/apache/james/adapter/mailbox/MailboxManagerManagementMBean.java, server/container/mailbox-adapter/src/test/java/org/apache/james/adapter/mailbox/MailboxManagementTest.java, server/container/mailbox-adapter/src/test/resources/eml/frnog.eml, src/site/markdown/server/manage-cli.md
Unit tests and follow up for https://github.com/apache/james-project/pull/69
I will add a documentation commit in the beginning of the afternoon... (http://james.apache.org/server/manage-cli.html for new commands details)
=> JAMES-2081 ImportEml CLI  command

backends-common/cassandra/src/main/java/org/apache/james/backends/cassandra/versions/CassandraSchemaVersionManager.java, mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageDAO.java, mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageDAOV2.java, mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/migration/Migration.java, mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/migration/V1ToV2Migration.java, mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/migration/V1ToV2MigrationTest.java, server/container/guice/cassandra-guice/pom.xml, server/container/guice/cassandra-guice/src/main/java/org/apache/james/CassandraJamesServerMain.java, server/container/guice/pom.xml, server/container/guice/protocols/webadmin-cassandra/pom.xml, server/container/guice/protocols/webadmin-cassandra/src/main/java/org/apache/james/modules/server/CassandraRoutesModule.java, server/pom.xml, server/protocols/webadmin-integration-test/src/test/java/org/apache/james/webadmin/integration/WebAdminServerIntegrationTest.java, server/protocols/webadmin/webadmin-cassandra/pom.xml, server/protocols/webadmin/webadmin-cassandra/src/main/java/org/apache/james/webadmin/dto/CassandraVersionRequest.java, server/protocols/webadmin/webadmin-cassandra/src/main/java/org/apache/james/webadmin/dto/CassandraVersionResponse.java, server/protocols/webadmin/webadmin-cassandra/src/main/java/org/apache/james/webadmin/routes/CassandraMigrationRoutes.java, server/protocols/webadmin/webadmin-cassandra/src/main/java/org/apache/james/webadmin/service/CassandraMigrationService.java, server/protocols/webadmin/webadmin-cassandra/src/main/java/org/apache/james/webadmin/service/MigrationException.java, server/protocols/webadmin/webadmin-cassandra/src/test/java/org/apache/james/webadmin/dto/VersionRequestTest.java, server/protocols/webadmin/webadmin-cassandra/src/test/java/org/apache/james/webadmin/routes/CassandraMigrationRoutesTest.java, server/protocols/webadmin/webadmin-cassandra/src/test/java/org/apache/james/webadmin/service/CassandraMigrationServiceTest.java, server/protocols/webadmin/webadmin-core/pom.xml, server/protocols/webadmin/webadmin-core/src/main/java/org/apache/james/webadmin/utils/JsonTransformer.java, src/site/markdown/server/manage-webadmin.md, src/site/xdoc/server/config-cassandra.xml
https://github.com/linagora/james-project/pull/906 rebased and fixuped.
=> JAMES-2096 Webadmin triggered migrations

dockerfiles/packaging/debian/package/etc/james/templates/webadmin.properties, dockerfiles/run/guice/cassandra-ldap/destination/conf/webadmin.properties, dockerfiles/run/guice/cassandra/destination/conf/webadmin.properties, server/container/guice/cassandra-guice/pom.xml, server/container/guice/cassandra-guice/src/main/java/org/apache/james/CassandraJamesServerMain.java, server/container/guice/memory-guice/sample-configuration/webadmin.properties, server/container/guice/pom.xml, server/container/guice/protocols/webadmin-swagger/pom.xml, server/container/guice/protocols/webadmin-swagger/src/main/java/org/apache/james/modules/server/SwaggerRoutesModules.java, server/container/guice/protocols/webadmin/src/main/java/org/apache/james/modules/server/WebAdminServerModule.java, server/pom.xml, server/protocols/webadmin-integration-test/src/test/java/org/apache/james/webadmin/integration/WebAdminServerIntegrationTest.java, server/protocols/webadmin-integration-test/src/test/resources/webadmin.properties, server/protocols/webadmin/webadmin-core/pom.xml, server/protocols/webadmin/webadmin-core/src/main/java/org/apache/james/webadmin/WebAdminConfiguration.java, server/protocols/webadmin/webadmin-core/src/test/java/org/apache/james/webadmin/WebAdminConfigurationTest.java, server/protocols/webadmin/webadmin-data/src/main/java/org/apache/james/webadmin/routes/DomainRoutes.java, server/protocols/webadmin/webadmin-data/src/main/java/org/apache/james/webadmin/routes/UserRoutes.java, server/protocols/webadmin/webadmin-mailbox/src/main/java/org/apache/james/webadmin/routes/GlobalQuotaRoutes.java, server/protocols/webadmin/webadmin-mailbox/src/main/java/org/apache/james/webadmin/routes/UserMailboxesRoutes.java, server/protocols/webadmin/webadmin-swagger/pom.xml, server/protocols/webadmin/webadmin-swagger/src/main/java/org/apache/james/webadmin/swagger/SwaggerParser.java, server/protocols/webadmin/webadmin-swagger/src/main/java/org/apache/james/webadmin/swagger/routes/SwaggerRoutes.java
- It exposes new API which contain swagger json value
- It still contains hard code to point to the james webadmin server --> need to find a way to configure it
=> JAMES-2099: Add James REST API to expose the swagger API

server/container/guice/cassandra-guice/pom.xml, server/container/guice/es-metric-reporter/pom.xml, server/container/guice/es-metric-reporter/src/main/java/org/apache/james/modules/server/ESMetricReporterModule.java, server/container/guice/jpa-guice/pom.xml, server/container/guice/jpa-guice/src/main/java/org/apache/james/JPAJamesServerMain.java, server/container/guice/jpa-smtp/pom.xml, server/container/guice/jpa-smtp/src/main/java/org/apache/james/JPAJamesServerMain.java, server/container/guice/pom.xml
Orthogonal, Apache ticketed verison of https://github.com/linagora/james-project/pull/721
=> JAMES-2128 All guice product should support out of the box ES metics and ES logs

server/container/guice/cassandra-guice/src/main/java/org/apache/james/modules/mailbox/CassandraMailboxModule.java
This avoid re-preparing the queries defined in this DAO
=> MAILBOX−309 Bind CassandraAttachmentMessageIdDAO as SINGLETON

mailet/base/src/test/java/org/apache/mailet/base/test/MimeMessageBuilder.java, mailet/standard/src/main/java/org/apache/james/transport/matchers/HasMimeType.java, mailet/standard/src/test/java/org/apache/james/transport/matchers/HasMimeTypeTest.java
Added HasMimeType matcher and tests.
Play CI against Hacktoberfest contribution: https://github.com/apache/james-project/pull/73
=> JAMES-2157 Added HasMimeType matcher and tests.

server/app/src/main/resources/recipientrewritetable.xml
The original PR is here: https://github.com/apache/james-project/pull/74
=> JAMES-2194 external contrib from Pascal

protocols/smtp/src/main/java/org/apache/james/protocols/smtp/core/AbstractHookableCmdHandler.java, server/protocols/protocols-library/src/main/java/org/apache/james/protocols/lib/netty/JMXEnabledOrderedMemoryAwareThreadPoolExecutor.java
https://github.com/apache/james-project/pull/75 duplicated for CI
=> PR duplication of https://github.com/apache/james-project/pull/75 for CI

server/container/guice/protocols/jmap/src/main/java/org/apache/james/utils/MessageIdProbe.java, server/protocols/jmap-integration-testing/cassandra-jmap-integration-testing/src/test/java/org/apache/james/jmap/cassandra/cucumber/CassandraKeywordsConsistencyOnDelegationMailboxTest.java, server/protocols/jmap-integration-testing/jmap-integration-testing-common/src/test/java/org/apache/james/jmap/methods/integration/cucumber/DownloadStepdefs.java, server/protocols/jmap-integration-testing/jmap-integration-testing-common/src/test/java/org/apache/james/jmap/methods/integration/cucumber/GetMessageListMethodStepdefs.java, server/protocols/jmap-integration-testing/jmap-integration-testing-common/src/test/java/org/apache/james/jmap/methods/integration/cucumber/GetMessagesMethodStepdefs.java, server/protocols/jmap-integration-testing/jmap-integration-testing-common/src/test/java/org/apache/james/jmap/methods/integration/cucumber/ImapStepdefs.java, server/protocols/jmap-integration-testing/jmap-integration-testing-common/src/test/java/org/apache/james/jmap/methods/integration/cucumber/MailboxStepdefs.java, server/protocols/jmap-integration-testing/jmap-integration-testing-common/src/test/java/org/apache/james/jmap/methods/integration/cucumber/MainStepdefs.java, server/protocols/jmap-integration-testing/jmap-integration-testing-common/src/test/java/org/apache/james/jmap/methods/integration/cucumber/SetMessagesMethodStepdefs.java, server/protocols/jmap-integration-testing/jmap-integration-testing-common/src/test/java/org/apache/james/jmap/methods/integration/cucumber/UploadStepdefs.java, server/protocols/jmap-integration-testing/jmap-integration-testing-common/src/test/java/org/apache/james/jmap/methods/integration/cucumber/UserStepdefs.java, server/protocols/jmap-integration-testing/jmap-integration-testing-common/src/test/resources/cucumber/ImapKeywordsConsistency.feature, server/protocols/jmap-integration-testing/jmap-integration-testing-common/src/test/resources/cucumber/ImapSetMessagesMailboxesUpdatesCompatibility.feature, server/protocols/jmap-integration-testing/jmap-integration-testing-common/src/test/resources/cucumber/KeywordsConsistencyOnDelegationMailbox.feature, server/protocols/jmap-integration-testing/memory-jmap-integration-testing/src/test/java/org/apache/james/jmap/memory/cucumber/MemoryKeywordsConsistencyOnDelegationMailboxTest.java, server/testing/pom.xml, server/testing/src/main/java/org/apache/james/utils/IMAPMessageReader.java, server/testing/src/test/java/org/apache/james/utils/IMAPMessageReaderTest.java
New build triggering (replaces #1060)
=> James 2183

mailbox/api/src/main/java/org/apache/james/mailbox/model/MailboxPath.java
This logic will be handled at protocol layer
=> PROTOCOLS-117 Bonus: Remove unused  MailboxPath parsing method

dockerfiles/compilation/java-8/Dockerfile, dockerfiles/packaging/debian/package.sh
Replaces https://github.com/apache/james-project/pull/82
=> James 2212 Fix Debian packaging

backends-common/cassandra/src/test/java/org/apache/james/backends/cassandra/ContainerLifecycleConfiguration.java, mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/CassandraMessageIdManagerStorageTest.java, mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageMapperTest.java, server/protocols/jmap-integration-testing/cassandra-jmap-integration-testing/src/test/java/org/apache/james/jmap/cassandra/CassandraGetMailboxesMethodTest.java, server/protocols/jmap-integration-testing/cassandra-jmap-integration-testing/src/test/java/org/apache/james/jmap/cassandra/CassandraGetMessageListMethodTest.java, server/protocols/jmap-integration-testing/cassandra-jmap-integration-testing/src/test/java/org/apache/james/jmap/cassandra/CassandraGetVacationResponseTest.java, server/protocols/jmap-integration-testing/cassandra-jmap-integration-testing/src/test/java/org/apache/james/jmap/cassandra/CassandraJmapAuthenticationTest.java, server/protocols/jmap-integration-testing/cassandra-jmap-integration-testing/src/test/java/org/apache/james/jmap/cassandra/CassandraSetMailboxesMethodTest.java, server/protocols/jmap-integration-testing/cassandra-jmap-integration-testing/src/test/java/org/apache/james/jmap/cassandra/CassandraSetMessagesMethodTest.java, server/protocols/jmap-integration-testing/cassandra-jmap-integration-testing/src/test/java/org/apache/james/jmap/cassandra/CassandraSetVacationResponseTest.java, server/protocols/jmap-integration-testing/cassandra-jmap-integration-testing/src/test/java/org/apache/james/jmap/cassandra/CassandraUserProvisionningConcurrencyTest.java, server/protocols/jmap-integration-testing/cassandra-jmap-integration-testing/src/test/java/org/apache/james/jmap/cassandra/CassandraVacationIntegrationTest.java, server/protocols/jmap-integration-testing/cassandra-jmap-integration-testing/src/test/java/org/apache/james/jmap/cassandra/CassandraVacationRelayIntegrationTest.java
Rebase + taking care of comments of this PR:
https://github.com/linagora/james-project/pull/1128/commits
=> JAMES-2221 Ensure Cassandra container is well restarted in Cassandra JMAP integration tests

server/protocols/jmap-integration-testing/jmap-integration-testing-common/src/test/java/org/apache/james/jmap/methods/integration/SetMessagesMethodTest.java, server/protocols/jmap-integration-testing/jmap-integration-testing-common/src/test/java/org/apache/james/jmap/methods/integration/cucumber/SetMessagesMethodStepdefs.java, server/protocols/jmap-integration-testing/jmap-integration-testing-common/src/test/resources/cucumber/SetMessages.feature, server/protocols/jmap/src/main/java/org/apache/james/jmap/methods/MessageAppender.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/methods/SetMessagesCreationProcessor.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/methods/SetMessagesUpdateProcessor.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/model/CreationMessage.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/model/Keywords.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/model/OldKeyword.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/model/UpdateMessagePatch.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/utils/KeywordsCombiner.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/json/ParsingWritingObjects.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/model/CreationMessageTest.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/model/KeywordsTest.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/model/OldKeywordTest.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/model/UpdateMessagePatchTest.java
I have done the usages of optional of _OldKeywords_ with an old **if**,
then it will be easier to drop this feature in the future.
=> JAMES-2232 Flags in JMAP should be handled by Keywords & is attributes

server/protocols/jmap/src/main/java/org/apache/james/jmap/send/PostDequeueDecorator.java
Playing tests for https://github.com/apache/james-project/pull/78
=> Delete redundant null checks

protocols/smtp/src/main/java/org/apache/james/protocols/smtp/core/RcptCmdHandler.java, server/data/data-jdbc/src/main/java/org/apache/james/mailrepository/jdbc/JDBCMailRepository.java, server/data/data-library/src/main/java/org/apache/james/domainlist/lib/AbstractDomainList.java, server/mailet/mailetcontainer-camel/src/main/java/org/apache/james/mailetcontainer/impl/JamesMailetContext.java, server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/BayesianAnalysis.java, server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/delivery/MailDispatcher.java
Integration testing for https://github.com/apache/james-project/pull/80
=> Misc improvements - Community integration testing

protocols/imap/src/main/java/org/apache/james/imap/api/ImapSessionUtils.java, protocols/imap/src/test/java/org/apache/james/imap/api/ImapSessionUtilsTest.java
Reopen of https://github.com/linagora/james-project/pull/1191 with a proper branch name
=> JAMES-2261 Hotfix/imap utils mailbox nullcheck (community)

server/app/src/main/resources/mailetcontainer.xml
Unit testing for https://github.com/apache/james-project/pull/90 .
Please review.
=> JAMES-2265 Correct RemoteDelivery default configuration (community)

src/site/xdoc/server/config-mailetcontainer.xml, src/site/xdoc/server/feature-mailetcontainer.xml
Also ship some additional links and corrections to ease documentation reading.
=> JAMES-2263 Document mailet error handling

mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/quota/CassandraPerUserMaxQuotaManager.java
We should rather rely on a more generic prepared query.
=> MAILBOX-323 Avoid non prepared query recycling

src/homepage/index.html
Reopen of already approuved PR https://github.com/linagora/james-project/pull/1331
Due to a false click merging the PR
=> JAMES-2356 Fix typo

core/src/main/java/org/apache/james/core/builder/MimeMessageBuilder.java, core/src/test/java/org/apache/james/core/builder/MimeMessageBuilderTest.java, server/protocols/webadmin/webadmin-core/pom.xml, server/protocols/webadmin/webadmin-core/src/main/java/org/apache/james/webadmin/utils/JsonTransformer.java, server/protocols/webadmin/webadmin-mailrepository/pom.xml, server/protocols/webadmin/webadmin-mailrepository/src/main/java/org/apache/james/webadmin/dto/HeadersDto.java, server/protocols/webadmin/webadmin-mailrepository/src/main/java/org/apache/james/webadmin/dto/InaccessibleFieldException.java, server/protocols/webadmin/webadmin-mailrepository/src/main/java/org/apache/james/webadmin/dto/MailDto.java, server/protocols/webadmin/webadmin-mailrepository/src/main/java/org/apache/james/webadmin/routes/MailRepositoriesRoutes.java, server/protocols/webadmin/webadmin-mailrepository/src/main/java/org/apache/james/webadmin/service/MailRepositoryStoreService.java, server/protocols/webadmin/webadmin-mailrepository/src/test/java/org/apache/james/webadmin/routes/MailRepositoriesRoutesTest.java
Continuation of #1454 (for CI)
=> JAMES-2321 WebAdmin should allow to see more details about Mails

server/protocols/webadmin/webadmin-data/src/main/java/org/apache/james/webadmin/dto/DLPConfigurationItemDTO.java, server/protocols/webadmin/webadmin-data/src/test/java/org/apache/james/webadmin/dto/DLPConfigurationItemDTOTest.java
I did a bug in DLP Webadmin, `DLPConfigurationItemDTO` is not well created 😢
=> fixup! JAMES-2428 correct DTO creation (a DLP webadmin bug)

server/data/data-jdbc/src/test/java/org/apache/james/mailrepository/jdbc/JDBCMailRepositoryTest.java
Just removed disabled test that actually passes.
Opened here for CI, cf https://github.com/apache/james-project/pull/130
=> JAMES-2304 JDBC Mail repository do not allow content update.

server/container/guice/cassandra-guice/src/test/java/org/apache/james/ESReporterTest.java, server/data/data-jmap/pom.xml, server/data/data-jmap/src/main/java/org/apache/james/jmap/api/filtering/FilteringManagement.java, server/data/data-jmap/src/main/java/org/apache/james/jmap/api/filtering/Rule.java, server/data/data-jmap/src/main/java/org/apache/james/jmap/api/filtering/impl/DefineRulesCommand.java, server/data/data-jmap/src/main/java/org/apache/james/jmap/api/filtering/impl/DefineRulesCommandHandler.java, server/data/data-jmap/src/main/java/org/apache/james/jmap/api/filtering/impl/EventSourcingFilteringManagement.java, server/data/data-jmap/src/main/java/org/apache/james/jmap/api/filtering/impl/FilteringAggregate.java, server/data/data-jmap/src/main/java/org/apache/james/jmap/api/filtering/impl/FilteringAggregateId.java, server/data/data-jmap/src/main/java/org/apache/james/jmap/api/filtering/impl/RuleSetDefined.java, server/data/data-jmap/src/test/java/org/apache/james/jmap/api/filtering/FilteringAggregateIdTest.java, server/data/data-jmap/src/test/java/org/apache/james/jmap/api/filtering/FilteringManagementContract.java, server/data/data-jmap/src/test/java/org/apache/james/jmap/api/filtering/RuleTest.java, server/data/data-jmap/src/test/java/org/apache/james/jmap/api/filtering/impl/DefineRulesCommandTest.java, server/data/data-jmap/src/test/java/org/apache/james/jmap/api/filtering/impl/EventSourcingFilteringManagementTest.java, server/protocols/jmap-integration-testing/jmap-integration-testing-common/src/test/java/org/apache/james/jmap/TestingConstants.java, server/protocols/jmap-integration-testing/jmap-integration-testing-common/src/test/java/org/apache/james/jmap/methods/integration/ForwardIntegrationTest.java, server/protocols/webadmin/webadmin-mailrepository/src/test/java/org/apache/james/webadmin/routes/MailRepositoriesRoutesTest.java
continue matthieu works (#1671)
fixup some comments from benoits and let the PR have a decent name :)
=> JAMES-2528 [Filter] Implement event sourced filter

grafana-reporting/Tika-1522226794419.json
=> MAILBOX-338 Correct dashboard for gauges

backends-common/rabbitmq/src/test/java/org/apache/james/backend/rabbitmq/DockerClusterRabbitMQExtension.java, backends-common/rabbitmq/src/test/java/org/apache/james/backend/rabbitmq/DockerRabbitMQ.java, mpt/impl/smtp/core/src/main/java/org/apache/james/mpt/smtp/ForwardSmtpTest.java, server/mailet/integration-testing/src/test/java/org/apache/james/mailets/DirectResolutionRemoteDeliveryIntegrationTest.java, server/mailet/integration-testing/src/test/java/org/apache/james/mailets/GatewayRemoteDeliveryIntegrationTest.java, server/mailet/integration-testing/src/test/java/org/apache/james/smtp/SmtpAuthorizedAddressesTest.java, server/mailet/integration-testing/src/test/java/org/apache/james/transport/mailets/GroupMappingRelayTest.java, server/protocols/jmap-integration-testing/jmap-integration-testing-common/src/test/java/org/apache/james/jmap/VacationRelayIntegrationTest.java, server/testing/src/main/java/org/apache/james/utils/FakeSmtp.java
a step by step version of https://github.com/linagora/james-project/pull/1760 with some alternative choices
=> Rabbitmq build stability

server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/RabbitMQManagementApi.java
The RabbitMQ management API seems easy to overwhelm and returns 500 quickly
when tested parallely. Adding a simple delayed retry makes the tests more robust
(from 50% failures to non noticeable)
=> JAMES-2544 Add a retry policy to stabilize RabbitMQ management API

backends-common/rabbitmq/src/test/java/org/apache/james/backend/rabbitmq/RabbitMQClusterTest.java
=> JAMES-2577 Disable unstable RabbitMQClusterTest

mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMailboxMapper.java, mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageDAO.java, server/container/util/src/main/java/org/apache/james/util/CompletableFutureUtil.java, server/container/util/src/test/java/org/apache/james/util/CompletableFutureUtilTest.java, server/data/data-cassandra/src/main/java/org/apache/james/sieve/cassandra/CassandraSieveRepository.java, server/protocols/jmap/src/main/java/org/apache/james/jmap/mailet/VacationMailet.java
Using thenCombine is more appropriate than using a custom thenCompose.
Note that it also adds a ~10% execution speed improvement.
=> JAMES-1925 Simplify CompletableFutureUtil::allOf

mailet/api/src/main/java/org/apache/mailet/Mail.java, mailet/api/src/test/java/org/apache/mailet/ContractMailTest.java, mailet/test/pom.xml, mailet/test/src/main/java/org/apache/mailet/base/test/FakeMail.java, mailet/test/src/test/java/org/apache/mailet/base/test/FakeMailTest.java, pom.xml, server/container/core/pom.xml, server/container/core/src/main/java/org/apache/james/server/core/MailImpl.java, server/container/core/src/test/java/org/apache/james/server/core/MailHeadersTest.java, server/container/core/src/test/java/org/apache/james/server/core/MailImplTest.java, server/container/core/src/test/java/org/apache/james/server/core/MimeMessageCopyOnWriteProxyTest.java, server/container/core/src/test/java/org/apache/james/server/core/MimeMessageInputStreamSourceTest.java, server/container/core/src/test/java/org/apache/james/server/core/MimeMessageTest.java, server/container/core/src/test/java/org/apache/james/server/core/MimeMessageUtilTest.java, server/container/core/src/test/java/org/apache/james/server/core/MimeMessageWrapperTest.java, server/container/core/src/test/java/org/apache/james/server/core/filesystem/SimpleUrlTest.java
=> JAMES-2578 Add new Mailet API

backends-common/rabbitmq/pom.xml, backends-common/rabbitmq/src/test/java/org/apache/james/backend/rabbitmq/RabbitMQExtension.java, backends-common/rabbitmq/src/test/java/org/apache/james/backend/rabbitmq/RabbitMQHealthCheckTest.java, backends-common/rabbitmq/src/test/java/org/apache/james/backend/rabbitmq/RabbitMQTest.java, mailbox/jcr/pom.xml, mailbox/jcr/src/test/resources/logback-test.xml, mpt/impl/imap-mailbox/jpa/pom.xml, server/blob/blob-objectstorage/pom.xml, server/mailet/integration-testing/pom.xml, server/protocols/jmap-integration-testing/memory-jmap-integration-testing/pom.xml, server/queue/queue-rabbitmq/src/test/java/org/apache/james/queue/rabbitmq/RabbitMQMailQueueConfigurationChangeTest.java, server/queue/queue-rabbitmq/src/test/java/org/apache/james/queue/rabbitmq/RabbitMQMailQueueTest.java, server/queue/queue-rabbitmq/src/test/java/org/apache/james/queue/rabbitmq/RabbitMqMailQueueFactoryTest.java
Before 
```
[INFO] Apache James :: Mailbox :: JCR ..................... SUCCESS [02:42 min]
[INFO] Apache James MPT Imap Mailbox - JPA ................ SUCCESS [03:08 min]
[INFO] Apache James :: Server :: Blob :: Object storage ... SUCCESS [03:51 min]
[INFO] Apache James RabbitMQ backend ...................... SUCCESS [05:04 min]
[INFO] Apache James :: Server :: Mailets Integration Testing SUCCESS [05:30 min]
[INFO] Apache James :: Server :: Mail Queue :: RabbitMQ ... SUCCESS [09:28 min]
[INFO] Apache James :: Server :: JMAP :: Memory Integration testing SUCCESS [12:16 min]
```
After
```
[INFO] Apache James :: Mailbox :: JCR ..................... SUCCESS [ 24.334 s] (-1 min 18s)
[INFO] Apache James MPT Imap Mailbox - JPA ................ SUCCESS [01:18 min] (-1 min 50s)
[INFO] Apache …
```
=> JAMES-2489 Continue refining build time

server/container/guice/blob-objectstorage-guice/src/test/java/org/apache/james/modules/objectstorage/FakePropertiesProvider.java, server/container/guice/cassandra-rabbitmq-guice/pom.xml, server/container/guice/cassandra-rabbitmq-guice/src/main/java/org/apache/james/modules/objectstore/BlobStoreChoosingConfiguration.java, server/container/guice/cassandra-rabbitmq-guice/src/main/java/org/apache/james/modules/objectstore/BlobStoreChoosingModule.java, server/container/guice/cassandra-rabbitmq-guice/src/test/java/org/apache/james/modules/objectstore/BlobStoreChoosingConfigurationTest.java, server/container/guice/cassandra-rabbitmq-guice/src/test/java/org/apache/james/modules/objectstore/BlobStoreChoosingModuleTest.java
=> JAMES-2582 Configuration file for choosing blob store impl

dockerfiles/run/spring/Dockerfile
Fix version used in spring dockerfile
=> [maven-release-plugin] prepare for next development iteration

backends-common/elasticsearch/src/test/java/org/apache/james/backends/es/ElasticSearchIndexerTest.java, backends-common/rabbitmq/src/test/java/org/apache/james/backend/rabbitmq/RabbitMQConnectionFactoryTest.java, core/src/main/java/org/apache/james/core/MailAddress.java, core/src/main/java/org/apache/james/core/MaybeSender.java, core/src/test/java/org/apache/james/core/MailAddressTest.java, mailbox/api/src/test/java/org/apache/james/mailbox/MailboxManagerTest.java, mailet/base/src/test/java/org/apache/mailet/base/MailetPipelineLoggingTest.java, mailet/standard/src/main/java/org/apache/james/transport/matchers/SenderDomainIs.java, protocols/smtp/src/test/java/org/apache/james/protocols/smtp/core/fastfail/MaxRcptHandlerTest.java, server/container/core/src/main/java/org/apache/james/server/core/MailImpl.java, server/data/data-ldap/src/test/java/org/apache/james/user/ldap/ReadOnlyUsersLDAPRepositoryTest.java, server/protocols/jmap/src/test/java/org/apache/james/jmap/model/KeywordsTest.java, server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/view/cassandra/EnqueuedMailsDAO.java, third-party/spamassassin/src/test/java/org/apache/james/spamassassin/SpamAssassinExtension.java
Fix some warnings introduced by the introduction of maybe sender
=> James 2557 warnings

server/protocols/jmap/pom.xml, server/protocols/jmap/src/main/java/org/apache/james/jmap/mailet/VacationMailet.java
Just ed5e38a
If you agree with this, I'll create a JIRA and update the commit comment
=>  Reactor version for vacation mailet: don't use the Cassandra thread pool to wait for an other Cassandra request

mpt/impl/smtp/cassandra-rabbitmq-swift/src/test/java/org/apache/james/mpt/smtp/CassandraRabbitMQSwiftSmtpTestRule.java, server/container/guice/cassandra-guice/src/test/java/org/apache/james/CassandraJmapTestRule.java, server/container/guice/cassandra-rabbitmq-guice/src/test/java/org/apache/james/CassandraRabbitMQSwiftJmapTestRule.java, server/container/guice/guice-common/src/main/java/org/apache/james/CleanupTasksPerformer.java, server/container/guice/guice-common/src/main/java/org/apache/james/GuiceJamesServer.java, server/container/guice/guice-common/src/test/java/org/apache/james/JamesServerExtensionBuilder.java, server/container/guice/memory-guice/src/test/java/org/apache/james/GuiceLifecycleHeathCheckTest.java, server/protocols/jmap-integration-testing/cassandra-jmap-integration-testing/src/test/java/org/apache/james/jmap/cassandra/cucumber/CassandraStepdefs.java, server/protocols/jmap-integration-testing/rabbitmq-jmap-integration-testing/src/test/java/org/apache/james/jmap/rabbitmq/cucumber/RabbitMQStepdefs.java, server/protocols/webadmin-integration-test/src/test/java/org/apache/james/webadmin/integration/CassandraJmapExtension.java
I will link it to JAMES-2470 once green
=> implement cleanup tasks as a @PreDestroy component

mailbox/api/src/main/java/org/apache/james/mailbox/events/RetryBackoff.java, mailbox/api/src/main/java/org/apache/james/mailbox/events/RetryBackoffConfiguration.java, mailbox/api/src/test/java/org/apache/james/mailbox/events/ErrorHandlingContract.java, mailbox/api/src/test/java/org/apache/james/mailbox/events/EventBusTestFixture.java, mailbox/api/src/test/java/org/apache/james/mailbox/events/RetryBackoffConfigurationTest.java, mailbox/event/event-rabbitmq/src/main/java/org/apache/james/mailbox/events/GroupConsumerRetry.java, mailbox/event/event-rabbitmq/src/main/java/org/apache/james/mailbox/events/GroupRegistration.java, mailbox/event/event-rabbitmq/src/main/java/org/apache/james/mailbox/events/GroupRegistrationHandler.java, mailbox/event/event-rabbitmq/src/main/java/org/apache/james/mailbox/events/RabbitMQEventBus.java, mailbox/event/event-rabbitmq/src/main/java/org/apache/james/mailbox/events/WaitDelayGenerator.java, mailbox/event/event-rabbitmq/src/test/java/org/apache/james/mailbox/events/RabbitMQEventBusTest.java, mailbox/event/event-rabbitmq/src/test/java/org/apache/james/mailbox/events/WaitDelayGeneratorTest.java
=> MAILBOX-372 RabbitMQEventBus exponential backoff

backends-common/cassandra/pom.xml, backends-common/cassandra/src/test/java/org/apache/james/backends/cassandra/components/CassandraTableTest.java
=> upgrade cassandra driver to last stable

mailbox/backup/pom.xml, mailbox/backup/src/main/java/org/apache/james/mailbox/backup/ArchiveService.java, mailbox/backup/src/main/java/org/apache/james/mailbox/backup/DefaultMailboxBackup.java, mailbox/backup/src/main/java/org/apache/james/mailbox/backup/MailboxBackup.java, mailbox/backup/src/main/java/org/apache/james/mailbox/backup/Zipper.java, mailbox/backup/src/test/java/org/apache/james/mailbox/backup/DefaultMailboxBackupTest.java, mailbox/backup/src/test/java/org/apache/james/mailbox/backup/MailboxMessageFixture.java, mailbox/backup/src/test/java/org/apache/james/mailbox/backup/ZipperTest.java, pom.xml
[Export] Backup API
This internal API will take an account in parameter and will export the folders and the mails as an archive stored into the Blob Store.
=> James 2681 [Export] Backup API

backends-common/cassandra/src/test/java/org/apache/james/backends/cassandra/DockerCassandra.java, pom.xml
Benefits: ryuk containers not being destroyed -> fixed
=> JAMES-2728 Upgrade testcontainers to 1.11.1

server/blob/blob-api/src/main/java/org/apache/james/blob/api/BlobStore.java, server/blob/blob-api/src/test/java/org/apache/james/blob/api/BlobStoreContract.java, server/blob/blob-api/src/test/java/org/apache/james/blob/api/MetricableBlobStoreContract.java, server/blob/blob-cassandra/src/main/java/org/apache/james/blob/cassandra/CassandraBlobsDAO.java, server/blob/blob-cassandra/src/test/java/org/apache/james/blob/cassandra/CassandraBlobsDAOTest.java, server/blob/blob-export-file/src/test/java/org/apache/james/blob/export/file/LocalFileBlobExportMechanismTest.java, server/blob/blob-objectstorage/src/main/java/org/apache/james/blob/objectstorage/ObjectStorageBlobsDAO.java, server/blob/blob-objectstorage/src/test/java/org/apache/james/blob/objectstorage/ObjectStorageBlobsDAOContract.java, server/blob/blob-objectstorage/src/test/java/org/apache/james/blob/objectstorage/ObjectStorageBlobsDAOTest.java, server/blob/blob-union/src/main/java/org/apache/james/blob/union/UnionBlobStore.java, server/blob/blob-union/src/test/java/org/apache/james/blob/union/UnionBlobStoreTest.java, third-party/linshare/src/test/java/org/apache/james/linshare/LinshareBlobExportMechanismTest.java
Decided to add a save for Strings method in the blob store after discussion with @mbaechler here : https://github.com/linagora/james-project/pull/2310#discussion_r276571030
=> JAMES-2741 refactor blobstore save

dockerfiles/compilation/java-8/integration_tests.sh, mpt/impl/imap-mailbox/external-james/pom.xml, mpt/impl/imap-mailbox/external-james/src/test/java/org/apache/james/mpt/imapmailbox/external/james/DeploymentValidation.java, mpt/impl/imap-mailbox/external-james/src/test/java/org/apache/james/mpt/imapmailbox/external/james/ExternalJamesModule.java, mpt/impl/imap-mailbox/external-james/src/test/java/org/apache/james/mpt/imapmailbox/external/james/JamesDeploymentValidationTest.java, mpt/impl/imap-mailbox/external-james/src/test/java/org/apache/james/mpt/imapmailbox/external/james/host/ExternalJamesConfiguration.java, mpt/impl/imap-mailbox/external-james/src/test/java/org/apache/james/mpt/imapmailbox/external/james/host/ExternalJamesConfigurationEnvironnementVariables.java, mpt/impl/imap-mailbox/external-james/src/test/java/org/apache/james/mpt/imapmailbox/external/james/host/ExternalJamesImapHostSystem.java, mpt/impl/imap-mailbox/external-james/src/test/java/org/apache/james/mpt/imapmailbox/external/james/host/ExternalJamesSmtpHostSystem.java, mpt/impl/imap-mailbox/external-james/src/test/java/org/apache/james/mpt/imapmailbox/external/james/host/SmtpHostSystem.java
First step toward https://github.com/linagora/james-project/pull/2334.
Need to be merged at the same time as : 
https://github.com/linagora/james-jenkins/pull/152
=> James 2754 part 1 -  Add smtp Port parameter to deploiement validation test

server/container/guice/cassandra-guice/src/main/java/org/apache/james/modules/mailbox/CassandraSchemaVersionStartUpCheck.java, server/container/guice/cassandra-guice/src/main/java/org/apache/james/modules/mailbox/CassandraSessionModule.java, server/container/guice/cassandra-guice/src/test/java/org/apache/james/JamesCapabilitiesServerTest.java, server/container/guice/guice-common/src/main/java/org/apache/james/StartUpChecksPerformer.java, server/container/guice/guice-common/src/main/java/org/apache/james/modules/StartUpChecksModule.java, server/container/guice/guice-common/src/test/java/org/apache/james/StartUpChecksPerformerTest.java, server/container/guice/memory-guice/src/test/java/org/apache/james/GuiceJamesServerStartUpCheckTest.java, server/container/guice/protocols/jmap/pom.xml, server/container/guice/protocols/jmap/src/main/java/org/apache/james/jmap/JMAPModule.java, server/container/guice/protocols/jmap/src/test/java/org/apache/james/jmap/JMAPModuleTest.java, server/container/lifecycle-api/pom.xml, server/container/lifecycle-api/src/main/java/org/apache/james/lifecycle/api/StartUpCheck.java
Rework #2369. I created another PR to keep the work from the original one.
Change: returning bad result instead of throwing exceptions
=> (Rework #2369) JAMES-2763 Rely on StartUpChecks for MailboxManager version checking

mailbox/api/src/test/java/org/apache/james/mailbox/MailboxManagerTest.java, mailbox/backup/src/test/java/org/apache/james/mailbox/backup/DefaultMailboxBackupTest.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMailboxManager.java, server/mailet/mailets/src/test/java/org/apache/james/transport/mailets/delivery/MailboxAppenderTest.java
This validation may be needed in delete & rename .... mailboxes
Update: they already have that validation
=> JAMES-2621 MailboxManager should validate mailbox path when creating mailboxes

mailbox/event/event-rabbitmq/src/main/java/org/apache/james/mailbox/events/RabbitMQEventBus.java, mailbox/event/event-rabbitmq/src/test/java/org/apache/james/mailbox/events/RabbitMQEventBusTest.java
Fixes my post-merge comments on https://github.com/linagora/james-project/pull/2442
=> JAMES-2759 Various fixes

server/blob/blob-api/src/main/java/org/apache/james/blob/api/BlobStore.java, server/blob/blob-api/src/main/java/org/apache/james/blob/api/MetricableBlobStore.java, server/blob/blob-api/src/test/java/org/apache/james/blob/api/BlobStoreContract.java, server/blob/blob-api/src/test/java/org/apache/james/blob/api/BucketBlobStoreContract.java, server/blob/blob-api/src/test/java/org/apache/james/blob/api/DeleteBlobStoreContract.java, server/blob/blob-api/src/test/java/org/apache/james/blob/api/MetricableBlobStoreContract.java, server/blob/blob-cassandra/src/main/java/org/apache/james/blob/cassandra/CassandraBlobsDAO.java, server/blob/blob-cassandra/src/test/java/org/apache/james/blob/cassandra/CassandraBlobsDAOTest.java, server/blob/blob-memory/src/main/java/org/apache/james/blob/memory/MemoryBlobStore.java, server/blob/blob-memory/src/test/java/org/apache/james/blob/memory/MemoryBlobStoreTest.java, server/blob/blob-objectstorage/src/main/java/org/apache/james/blob/objectstorage/ObjectStorageBlobsDAO.java, server/blob/blob-objectstorage/src/test/java/org/apache/james/blob/objectstorage/ObjectStorageBlobsDAOAWSCryptoTest.java, server/blob/blob-objectstorage/src/test/java/org/apache/james/blob/objectstorage/ObjectStorageBlobsDAOAWSNamespaceTest.java, server/blob/blob-objectstorage/src/test/java/org/apache/james/blob/objectstorage/ObjectStorageBlobsDAOAWSPrefixAndNamespaceTest.java, server/blob/blob-objectstorage/src/test/java/org/apache/james/blob/objectstorage/ObjectStorageBlobsDAOAWSPrefixTest.java, server/blob/blob-objectstorage/src/test/java/org/apache/james/blob/objectstorage/ObjectStorageBlobsDAOAWSTest.java, server/blob/blob-objectstorage/src/test/java/org/apache/james/blob/objectstorage/ObjectStorageBlobsDAOTest.java, server/blob/blob-union/src/main/java/org/apache/james/blob/union/UnionBlobStore.java, server/blob/blob-union/src/test/java/org/apache/james/blob/union/UnionBlobStoreTest.java
First part of the delete BlobStore method with memory impl and the contract update. ObjectStorage will be separated into an other PR
=> JAMES-2829 delete blobstore memory implementation + contract

mailet/standard/src/main/java/org/apache/james/transport/mailets/RemoveMimeHeader.java, mailet/standard/src/main/java/org/apache/james/transport/mailets/RemoveMimeHeaderByPrefix.java, mailet/standard/src/main/java/org/apache/james/transport/matchers/HasHeader.java, mailet/standard/src/main/java/org/apache/james/transport/matchers/HasHeaderWithPrefix.java, mailet/standard/src/test/java/org/apache/james/transport/mailets/RemoveMimeHeaderByPrefixTest.java, mailet/standard/src/test/java/org/apache/james/transport/mailets/RemoveMimeHeaderTest.java, mailet/standard/src/test/java/org/apache/james/transport/matchers/HasHeaderTest.java, mailet/standard/src/test/java/org/apache/james/transport/matchers/HasHeaderWithPrefixTest.java
recipients
CI only
Review https://github.com/apache/james-project/pull/155 instead
=> [CI_ONLY] JAMES-2735 Update mailet and matcher that uses the headers and the per

server/protocols/webadmin/webadmin-data/src/main/java/org/apache/james/webadmin/routes/RegexMappingRoutes.java, server/protocols/webadmin/webadmin-data/src/test/java/org/apache/james/webadmin/routes/RegexMappingRoutesTest.java, src/site/markdown/server/manage-webadmin.md
- removeRegexMapping implementation.
- documentation finished and included.
=> JAMES-2844 RemoveRegexMappingRoutes implementation

pom.xml
`mvn test` keep failing with new version, for example the memory jmap integration test.
The log looks weird that it report a method not found but I still can see it in the junit library
```
WARNING: TestEngine with ID 'junit-vintage' failed to discover tests
java.lang.NoSuchMethodError: org.junit.platform.commons.util.ReflectionUtils.tryToReadFieldValue(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/Object;)Lorg/junit/platform/commons/function/Try;
at org.junit.vintage.engine.support.UniqueIdReader.apply(UniqueIdReader.java:47)
at org.junit.vintage.engine.support.UniqueIdReader.apply(UniqueIdReader.java:28)
at java.util.function.Function.lambda$andThen$1(Function.java:88)
at java.util.stream.Collectors.lambda$groupingBy$45(Collectors.java:907)
at …
```
=> Revert "JAMES-2855 Upgrade junit 5 dependencies"

mailbox/elasticsearch/src/main/java/org/apache/james/mailbox/elasticsearch/events/ElasticSearchListeningMessageSearchIndex.java, mailbox/elasticsearch/src/test/java/org/apache/james/mailbox/elasticsearch/events/ElasticSearchListeningMessageSearchIndexTest.java, mailbox/lucene/src/main/java/org/apache/james/mailbox/lucene/search/LuceneMessageSearchIndex.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/search/LazyMessageSearchIndex.java, mailbox/store/src/main/java/org/apache/james/mailbox/store/search/ListeningMessageSearchIndex.java, mailbox/tools/indexer/src/main/java/org/apache/mailbox/tools/indexer/ReIndexerPerformer.java, mailbox/tools/indexer/src/test/java/org/apache/mailbox/tools/indexer/CassandraReIndexerImplTest.java, mailbox/tools/indexer/src/test/java/org/apache/mailbox/tools/indexer/ReIndexerImplTest.java, server/container/guice/memory-guice/src/main/java/org/apache/james/FakeMessageSearchIndex.java, server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/routes/ReindexingRoutesTest.java
```
Before: 
Tons of logs...
MPT LuceneSearch Total time:  06:18 min
After:
0 logs
MPT LuceneSearch 
Total time:  21.881 s
```
Wooop!
=> JAMES-2883 SearchIndex should not attempt to read a deleted mailbox

src/adr/0002-make-taskmanager-distributed.md, src/adr/0003-distributed-workqueue.md, src/adr/0004-distributed-tasks-listing.md, src/adr/0005-distributed-task-termination-ackowledgement.md, src/adr/0006-task-serialization.md, src/adr/0007-distributed-task-cancellation.md, src/adr/0008-distributed-task-await.md
Replaces https://github.com/linagora/james-project/pull/2733
Status: accepted by @remk @mbaechler @rouazana , rejected by @chibenwa
=> JAMES-2813 Add Architecture Decision Record about Distributed Task Manager

protocols/imap/src/main/java/org/apache/james/imap/message/response/AbstractStatusResponseFactory.java, protocols/imap/src/main/java/org/apache/james/imap/message/response/UnpooledStatusResponseFactory.java, protocols/imap/src/test/java/org/apache/james/imap/api/message/response/AbstractStatusResponseFactoryTest.java, protocols/imap/src/test/java/org/apache/james/imap/message/response/UnpooledStatusResponseFactoryTest.java
This PR is an attempt to produce at least one small refactoring per day.
It has many goals:
* show the current state of our practices by refactoring old code to current standard
* make the codebase better one step at a time
* maybe inspire contributors to do the same
* force myself to explore parts of the code that I never read or touch
* fight my after-lunch lack of energy by doing small and easy things
* have a greener github commit graph
* probably fix bugs along the way
=> One fix per day #1

server/mailet/mailetcontainer-camel/src/main/java/org/apache/james/mailetcontainer/impl/JamesMailSpooler.java, server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/remote/delivery/DeliveryRunnable.java
Unacurrate time of 0 ms is always being reported...
=> JAMES-2949 Fix metric reporting upon dequeue

CHANGELOG.md, JenkinsfileStressTests.groovy, README.adoc, dockerfiles/run/docker-compose.yml, server/testing/src/main/java/org/apache/james/util/docker/Images.java, src/site/markdown/server/install/guice-cassandra-rabbitmq-swift.md, upgrade-instructions.md
Related to https://github.com/linagora/james-project/pull/2776
=> Changelog for RabbitMQ 3.8 update

core/src/main/java/org/apache/james/core/healthcheck/Result.java, core/src/test/java/org/apache/james/core/healthcheck/ComponentNameTest.java, core/src/test/java/org/apache/james/core/healthcheck/ResultTest.java, metrics/metrics-api/pom.xml, metrics/metrics-api/src/main/java/org/apache/james/metrics/api/Metric.java, metrics/metrics-api/src/test/java/org/apache/james/metrics/api/MetricContract.java, metrics/metrics-api/src/test/java/org/apache/james/metrics/api/MetricFactoryContract.java, metrics/metrics-dropwizard/pom.xml, metrics/metrics-dropwizard/src/main/java/org/apache/james/metrics/dropwizard/DropWizardMetric.java, metrics/metrics-dropwizard/src/main/java/org/apache/james/metrics/dropwizard/DropWizardMetricFactory.java, metrics/metrics-dropwizard/src/test/java/org/apache/james/metrics/dropwizard/DropWizardMetricFactoryTest.java, metrics/metrics-dropwizard/src/test/java/org/apache/james/metrics/dropwizard/DropWizardMetricTest.java, metrics/metrics-logger/pom.xml, metrics/metrics-logger/src/main/java/org/apache/james/metrics/logger/DefaultMetric.java, metrics/metrics-logger/src/main/java/org/apache/james/metrics/logger/DefaultMetricFactory.java, metrics/metrics-logger/src/test/java/org/apache/james/metrics/logger/DefaultMetricFactoryTest.java, metrics/metrics-logger/src/test/java/org/apache/james/metrics/logger/DefaultMetricTest.java, metrics/metrics-tests/pom.xml, metrics/metrics-tests/src/main/java/org/apache/james/metrics/tests/RecordingMetric.java, metrics/metrics-tests/src/main/java/org/apache/james/metrics/tests/RecordingMetricFactory.java, metrics/metrics-tests/src/test/java/org/apache/james/metrics/tests/RecordingMetricFactoryTest.java, metrics/metrics-tests/src/test/java/org/apache/james/metrics/tests/RecordingMetricTest.java, pom.xml, server/container/guice/cassandra-guice/src/main/java/org/apache/james/modules/data/CassandraJmapModule.java, server/container/guice/memory-guice/src/main/java/org/apache/james/modules/data/MemoryDataJmapModule.java, server/data/data-jmap/src/main/java/org/apache/james/jmap/api/projections/MessageFastViewProjectionHealthCheck.java, server/data/data-jmap/src/test/java/org/apache/james/jmap/api/projections/MessageFastViewProjectionHealthCheckTest.java, server/queue/queue-api/src/test/java/org/apache/james/queue/api/MailQueueMetricContract.java
=> [Prepare to merge] JAMES-3007 MessageFastViewProjection health check

server/blob/blob-api/pom.xml, server/blob/blob-api/src/test/java/org/apache/james/blob/api/MetricableBlobStoreContract.java, server/blob/blob-cassandra/pom.xml, server/blob/blob-memory/pom.xml, server/blob/blob-objectstorage/pom.xml
This enhancement improve build stability
=> JAMES-3104 Eventually publish blob store metrics

mailbox/backup/pom.xml, mailbox/plugin/deleted-messages-vault-cassandra/pom.xml, mailbox/plugin/deleted-messages-vault/pom.xml, server/protocols/webadmin/webadmin-mailbox-deleted-message-vault/pom.xml
See https://github.com/apache/james-project/pull/207
=> [CI_ONLY] NOREVIEW JAMES-3214 Add missing test scope

backends-common/cassandra/src/test/java/org/apache/james/backends/cassandra/Scenario.java, backends-common/cassandra/src/test/java/org/apache/james/backends/cassandra/TestingSessionTest.java, server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/Dequeuer.java, server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/Enqueuer.java, server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/MailQueueName.java, server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/RabbitMQMailQueueFactory.java, server/queue/queue-rabbitmq/src/test/java/org/apache/james/queue/rabbitmq/RabbitMQMailQueueTest.java
I had a doubt. Testing it proved mails we fail to load are discarded (at least until connection failure).
I would expect emails that we fail to load to be re-queued.
=> JAMES-3290 Mails failing to load should not be lost by dequeue 

server/protocols/webadmin/webadmin-jmap/src/test/java/org/apache/james/webadmin/data/jmap/RecomputeUserFastViewProjectionItemsRequestToTaskTest.java
It seems the last fixup I did on https://github.com/linagora/james-project/pull/3550 got forgotten in the merge. Quickly approve it please, master is broken
=> JAMES-2982 Improve Username validation error messages (fix master)

server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/EmailGetMethodContract.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/json/EmailGetSerializer.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/Email.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/EmailAddressGroup.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/EmailGet.scala, server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/EmailHeader.scala
=> JAMES-3379 Email/get specific parsed headers: asGroupedAddresses, MessageIds, Date, URLs 

server/protocols/webadmin-cli/src/main/java/org/apache/james/cli/domain/DomainExistCommand.java, server/protocols/webadmin-cli/src/main/java/org/apache/james/httpclient/DomainClient.java, server/protocols/webadmin-cli/src/test/java/org/apache/james/cli/DomainManageTest.java
Reopens https://github.com/linagora/james-project/pull/3997
=> JAMES-3400 James Webadmin Cli Domain Exist CommandFeature domainexist

server/container/guice/guice-common/src/main/java/org/apache/james/PeriodicalHealthChecks.java, server/container/guice/guice-common/src/test/java/org/apache/james/PeriodicalHealthChecksTest.java
If some checks exceeds the reporting period, we end up overrunning
intermediate buffers.
```
reactor.core.Exceptions$ErrorCallbackNotImplemented: reactor.core.Exceptions$OverflowException: Could not emit tick 6784 due to lack of requests (interval doesn't support small downstream requests that replenish slower than the ticks)
Caused by: reactor.core.Exceptions$OverflowException: Could not emit tick 6784 due to lack of requests (interval doesn't support small downstream requests that replenish slower than the ticks)
at reactor.core.Exceptions.failWithOverflow(Exceptions.java:234)
at reactor.core.publisher.FluxInterval$IntervalRunnable.run(FluxInterval.java:130)
at reactor.core.scheduler.PeriodicWorkerTask.call(PeriodicWorkerTask.java:59)
at …
```
=> JAMES-3117 PeriodicalHealthChecks should not fail upon slow checks

server/mailet/mock-smtp-server/src/main/java/org/apache/james/mock/smtp/server/ExtendedMailFromCommand.java, server/mailet/mock-smtp-server/src/main/java/org/apache/james/mock/smtp/server/ExtendedRcptToCommand.java
To answer the comment there: https://github.com/linagora/james-project/pull/4165#discussion_r552025229
=> JAMES-3431 Fix some exception variable names in MockSMTPServer
