linagora/james-project

- server/container/guice/guice-common/src/main/java/org/apache/james/jmap/JMAPCommonModule.java
- server/protocols/jmap-integration-testing/jmap-integration-testing-common/src/test/java/org/apache/james/jmap/methods/integration/cucumber/DownloadStepdefs.java
- server/protocols/jmap-integration-testing/jmap-integration-testing-common/src/test/resources/cucumber/DownloadEndpoint.feature
- server/protocols/jmap-integration-testing/jmap-integration-testing-common/src/test/resources/cucumber/DownloadGet.feature
- server/protocols/jmap/src/main/java/org/apache/james/jmap/AccessTokenAuthenticationStrategy.java
- server/protocols/jmap/src/main/java/org/apache/james/jmap/AuthenticationFilter.java
- server/protocols/jmap/src/main/java/org/apache/james/jmap/AuthenticationStrategy.java
- server/protocols/jmap/src/main/java/org/apache/james/jmap/JMAPServer.java
- server/protocols/jmap/src/main/java/org/apache/james/jmap/JWTAuthenticationStrategy.java
- server/protocols/jmap/src/main/java/org/apache/james/jmap/QueryParameterAccessTokenAuthenticationStrategy.java
- server/protocols/jmap/src/main/java/org/apache/james/jmap/crypto/SignedTokenFactory.java
- server/protocols/jmap/src/main/java/org/apache/james/jmap/model/AttachmentAccessToken.java
- server/protocols/jmap/src/main/java/org/apache/james/jmap/utils/HeadersAuthenticationExtractor.java
- server/protocols/jmap/src/test/java/org/apache/james/jmap/AccessTokenAuthenticationStrategyTest.java
- server/protocols/jmap/src/test/java/org/apache/james/jmap/AuthenticationFilterTest.java
- server/protocols/jmap/src/test/java/org/apache/james/jmap/JWTAuthenticationStrategyTest.java
- server/protocols/jmap/src/test/java/org/apache/james/jmap/QueryParameterAccessTokenAuthenticationStrategyTest.java
- server/protocols/jmap/src/test/java/org/apache/james/jmap/crypto/SignedTokenFactoryTest.java
- server/protocols/jmap/src/test/java/org/apache/james/jmap/crypto/SignedTokenManagerTest.java
- server/protocols/jmap/src/test/java/org/apache/james/jmap/utils/HeadersAuthenticationExtractorTest.java
Rebase + take care of comment published in #308 
Commit order is wrong on GitHub, real order is:
JAMES-1784 Authentication strategy should be responsible of extracting the authentication part from the request
JAMES-1784 Remove checkAuthorizationHeader in AuthenticationStrategy
JAMES-1784 Add QueryParameterAccessTokenAuthenticationStrategy
JAMES-1784 Add integration tests when downloading attachment with access token
> James 1784 - Attachment : handle query string on downloadUrl to manage signature (work on filters) 

- mailbox/api/src/main/java/org/apache/james/mailbox/model/MailboxAnnotationKey.java
- mailbox/api/src/test/java/org/apache/james/mailbox/model/MailboxAnnotationKeyTest.java
- mpt/impl/imap-mailbox/core/src/main/resources/org/apache/james/imap/scripts/Annotation.test
On RFC: https://www.ietf.org/rfc/rfc5464.txt
At the end of session "3.2.  Namespace of Entries" it said:
Entry names can have any number of components starting at 2, unless they fall under the vendor namespaces (i.e., have a /shared/vendor/   <vendor-token> or /private/vendor/<vendor-token> prefix as described  below), in which case they have at least 4 components.
> Mailbox 270: Entry names can have any number of components starting at 2, unless they fall under the vendor namespaces

- mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/model/impl/MessageParser.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/impl/MessageParserTest.java
- mailbox/store/src/test/resources/eml/unknownDisposition.eml
- server/protocols/jmap-integration-testing/jmap-integration-testing-common/src/test/java/org/apache/james/jmap/methods/integration/cucumber/GetMessagesMethodStepdefs.java
- server/protocols/jmap-integration-testing/jmap-integration-testing-common/src/test/resources/cucumber/GetMessages.feature
- server/protocols/jmap-integration-testing/jmap-integration-testing-common/src/test/resources/eml/inlinedMultipart.eml
- server/protocols/jmap/src/main/java/org/apache/james/jmap/model/MessageContentExtractor.java
- server/protocols/jmap/src/test/java/org/apache/james/jmap/model/MessageContentExtractorTest.java
@MichaelBailly reported in https://github.com/linagora/james-project/issues/435 a mail that was displayed without body.
The mail was not valid as it contains : 
- a html part inlined without Content-ID
- a text plain part inlined without  Content-ID
James was looking for the first html/text part to report that did not have Content-Disposition, hence returned empty bodies.
That being said, [RFC-2183](https://tools.ietf.org/html/rfc2183) states : 
> Inline   bodyparts should be presented in the order in which they occur
Hence, James behaviour did not comply with RFC statements.
James should : 
- Look first for a body part of specific MIME Type without content-disposition
- Then have a fallback method for poorly written MIME messages : take first inlined body part with Content-Disposition …
> James 1833 Fallback solution for all-inlined emails

- server/protocols/jmap/src/main/java/org/apache/james/jmap/model/Emailer.java
- server/protocols/jmap/src/main/java/org/apache/james/jmap/model/MessageFactory.java
- server/protocols/jmap/src/test/java/org/apache/james/jmap/model/EmailerTest.java
- server/protocols/jmap/src/test/java/org/apache/james/jmap/model/MessageFactoryTest.java
With the following pull request : 
- JMAP still validate EMailers when specified threw the API
- When retrieving a message sent by JMAP that have invalid addresses, Emailer generation do not crash, allowing the email to be read.
Note : I choosed not to replace invalid address as it conveys some information, even if not valid...
Note : I extended it and demonstrated it for several addresses : cc bcc, from and to
> James 1836 Jmap should not break on invalid From in mails

- mpt/impl/imap-mailbox/core/src/main/java/org/apache/james/mpt/imapmailbox/suite/Security.java
- mpt/impl/imap-mailbox/core/src/main/resources/org/apache/james/imap/scripts/SharedMailbox.test
- protocols/imap/src/main/java/org/apache/james/imap/api/display/HumanReadableText.java
- protocols/imap/src/main/java/org/apache/james/imap/main/DeniedAccessOnSharedMailboxException.java
- protocols/imap/src/main/java/org/apache/james/imap/main/PathConverter.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/AbstractAuthProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/AbstractMailboxProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/AbstractMessageRangeProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/AbstractSelectionProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/AppendProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/CreateProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/DeleteACLProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/DeleteProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/GetACLProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/GetAnnotationProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/GetQuotaRootProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/LSubProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/ListProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/ListRightsProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/MyRightsProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/RenameProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/SetACLProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/SetAnnotationProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/StatusProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/base/AbstractChainedProcessor.java
- protocols/imap/src/test/java/org/apache/james/imap/main/PathConverterTest.java
I reworked MailboxPath generation and improved it a bit. Someone can not access any mailbox he do not own.
About paths, if my username is **chibenwa** : 
- Path *toto* will point to *#private:chibenwa:toto*
- Path *#private.toto* will also point to *#private:chibenwa:toto* 
With #private username is implied to be yours (previous behaviour)
- Path *#other.toto* will point to *#other:null:toto*
With shared mailboxes, username component of MailboxPath is implied to be null.
Question : Do we modify MailboxPath to have Optional user ? It is some serious refactoring, so I want to have your opinion before doing it. We may delay it to shared mailbox implementation.
I keep other questions for shared mailbox implementation ;-)
> James 1838 Clarify shared mailbox access

- protocols/imap/src/main/java/org/apache/james/imap/decode/main/DefaultImapDecoder.java
- protocols/imap/src/main/java/org/apache/james/imap/decode/parser/UidCommandParser.java
We should be able to know wich command is being used after UID command
It might help us to better understand  some IMAP bugs as Thunderbird exclusively relies on UIDs
> JAMES-1846 Improve IMAP logging

- src/site/xdoc/download.xml
Was pointing on something built before maven-release plugin switch
This one is built on the right commit. (1 commit after)
> JAMES-1879 change target for download 3.0.0-beta5

- mailbox/hbase/src/main/java/org/apache/james/mailbox/hbase/mail/model/HBaseMailbox.java
- mailbox/jcr/src/main/java/org/apache/james/mailbox/jcr/mail/model/JCRMailbox.java
- mailbox/jpa/src/main/java/org/apache/james/mailbox/jpa/mail/JPAAnnotationMapper.java
- mailbox/jpa/src/main/java/org/apache/james/mailbox/jpa/mail/JPAMailboxMapper.java
- mailbox/jpa/src/main/java/org/apache/james/mailbox/jpa/mail/model/JPAMailbox.java
- mailbox/jpa/src/main/java/org/apache/james/mailbox/jpa/mail/model/openjpa/AbstractJPAMailboxMessage.java
- mailbox/jpa/src/main/java/org/apache/james/mailbox/jpa/mail/model/openjpa/JPAMailboxMessage.java
- mailbox/jpa/src/test/java/org/apache/james/mailbox/jpa/mail/JPAMapperProvider.java
- mailbox/jpa/src/test/java/org/apache/james/mailbox/jpa/mail/TransactionalMailboxMapper.java
- mailbox/lucene/src/test/java/org/apache/james/mailbox/lucene/search/LuceneMailboxMessageSearchIndexTest.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/model/Mailbox.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/model/impl/SimpleMailbox.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/MailboxEventDispatcherTest.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/ListMailboxAssert.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/ListMailboxAssertTest.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/MailboxMapperTest.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/MapperProvider.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/MessageMapperTest.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/MessageMoveTest.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/MessageWithAttachmentMapperTest.java
which are:
- Split MessageMapperTest into 2 parts: one with attachment and the another without attachment which should be work with JPA
- Make JPAMapperTests should be fine when enable MAILBOX
> MAILBOX-279: make the JPAMapperTests should work when enable MAILBOX and MESSAGE

- mailet/api/src/main/java/org/apache/mailet/Experimental.java
- mailet/mailetdocs-maven-plugin/pom.xml
- mailet/mailetdocs-maven-plugin/src/main/java/org/apache/james/mailet/AbstractMailetdocsReport.java
- mailet/mailetdocs-maven-plugin/src/main/java/org/apache/james/mailet/DefaultDescriptorsExtractor.java
- mailet/mailetdocs-maven-plugin/src/main/java/org/apache/james/mailet/MailetMatcherDescriptor.java
- mailet/mailetdocs-maven-plugin/src/test/java/org/apache/james/mailet/DefaultDescriptorsExtractorTest.java
- mailet/mailetdocs-maven-plugin/src/test/java/org/apache/james/mailet/ExperimentalMailet.java
- mailet/mailetdocs-maven-plugin/src/test/java/org/apache/james/mailet/NonExperimentalMailet.java
The matcher/mailet documentation is generated by the mailetdocs-maven-plugin.
The goal of this PR is to mark matchers/mailets not yet supported as experimental.
> JAMES-1881 Mark Matcher/Mailet as experimental

- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageIdDAO.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageIdMapper.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageMapper.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/MailboxDeleteDuringUpdateException.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageIdDAOTest.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/MessageIdMapperTest.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/MessageMapperTest.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/concurrency/ConcurrentTestRunner.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/concurrency/ConcurrentTestRunnerTest.java
- Flags Updates on something else than the last message
- Flags upates on duplicated mailboxIds
> Mailbox 285 Solve issues with flags update

- mailbox/api/src/main/java/org/apache/james/mailbox/MessageManager.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageMapper.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/AttachmentLoaderTest.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/search/SimpleMessageSearchIndex.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/search/AbstractMessageSearchIndexTest.java
- mpt/core/src/main/java/org/apache/james/mpt/protocol/FileProtocolSessionBuilder.java
- mpt/core/src/main/java/org/apache/james/mpt/protocol/ProtocolSession.java
- mpt/core/src/main/java/org/apache/james/mpt/protocol/ProtocolSessionBuilder.java
- mpt/impl/imap-mailbox/core/src/main/resources/org/apache/james/imap/scripts/FetchEnvelope.test
- server/container/util-java8/src/test/java/org/apache/james/util/OptionalConverterTest.java
- server/protocols/jmap/src/test/java/org/apache/james/jmap/DefaultMailboxesProvisioningFilterThreadTest.java
Output example:
```
...
15:26:35.268 [WARN ] o.a.c.s.StorageService - Generated random token [-5333134853874357262]. Random tokens will result in an unbalanced ring; see http://wiki.apache.org/cassandra/Operations
15:26:43.945 [WARN ] o.a.c.u.FBUtilities - Trigger directory doesn't exist, please create it and try again.
Time spent in 'append': 93 ms
Time spent in 'fetch': 50 ms
Time spent in 'fetch': 32 ms
15:26:47.335 [ERROR] c.d.d.c.ControlConnection - [Control connection] Cannot connect to any host, scheduling retry in 1000 milliseconds
...
```
i prefer to use System.out in order to log times, so those informations are easily to find in large logs & don't depends on the logger level configuration.
> MPT-36 Introduce TIMER mpt scripts command

- dockerfiles/run/guice/cassandra-ldap/destination/conf/webadmin.properties
- dockerfiles/run/guice/cassandra/destination/conf/webadmin.properties
- server/container/guice/guice-common/src/main/java/org/apache/james/modules/server/WebAdminServerModule.java
- server/protocols/webadmin-integration-test/src/test/java/org/apache/james/webadmin/integration/WebAdminConfigurationModule.java
- server/protocols/webadmin/pom.xml
- server/protocols/webadmin/src/main/java/org/apache/james/webadmin/FixedPort.java
- server/protocols/webadmin/src/main/java/org/apache/james/webadmin/HttpsConfiguration.java
- server/protocols/webadmin/src/main/java/org/apache/james/webadmin/WebAdminConfiguration.java
- server/protocols/webadmin/src/main/java/org/apache/james/webadmin/WebAdminServer.java
- server/protocols/webadmin/src/test/java/org/apache/james/webadmin/HttpsConfigurationTest.java
- server/protocols/webadmin/src/test/java/org/apache/james/webadmin/WebAdminConfigurationTest.java
Crafted with love with Dung !
- Class for encapsultating web admin configuration
- Class for HTTPS configuration
- Enable HTTPS
Unable to write an integration test with RestAssured. But manual checks works fine : 
```
% curl -XGET -k https://127.0.0.1:34895/domains                                                                                        
["horizon","localhost.","127.0.0.1"]
```
> Vn barcamp : enable HTTPS

- server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/LocalDelivery.java
- server/mailet/mailets/src/test/java/org/apache/james/transport/mailets/delivery/LocalDeliveryTest.java
No tests on RRT behaviour of LocalDelivery
Default configuration already integrate this.
No integration tests broken.
We can even deploy this without troubbles on OP.LNG.COM
> JAMES-1973 LocalDelivery should not compose RRT

- dockerfiles/run/spring/Dockerfile
A better alternative would be to pass current build version as a parameter to the dockerfile.
Hence we can set this as part of our CI script.
Note: I do not know how to remove version from appassembler...
> Correct versions in Spring dockerfile

- server/protocols/jmap/pom.xml
- server/protocols/jmap/src/main/java/org/apache/james/jmap/JMAPServer.java
Just add this logger in your logback configuration:
```
<logger name="http.jmap" level="DEBUG"/>
```
and then, we will have such logs:
```
2017-05-11 15:23:37,743 DEBUG [qtp1057468716-30] - [http.jmap]- Incoming Request: 797afde3-93fe-485c-bcf1-004e086fea3b
POST http://localhost:33030/jmap HTTP/1.1
Authorization: XXX
Accept: application/json, application/javascript, text/javascript
User-Agent: Apache-HttpClient/4.5.1 (Java/1.8.0_121)
Connection: keep-alive
Host: localhost:33030
Accept-Encoding: gzip,deflate
Content-Length: 69
Content-Type: application/json; charset=UTF-8
[["setMessages", {"update": {"1" : { "isUnread" : false } } }, "#0"]]
2017-05-11 15:23:37,964 DEBUG [qtp1057468716-30] - [http.jmap]- Outgoing Response: 797afde3-93fe-485c-bcf1-004e086fea3b
HTTP/1.1 200 OK …
```
> Add logs of http JMAP requests on /jmap endpoint

- server/container/guice/cassandra-guice/pom.xml
ES searchable logs with rotating indexes <3
Will try to plug Kibana...
The configuration used for ES APPENDER:
```
<appender name="ELASTIC" class="com.internetitem.logback.elasticsearch.ElasticsearchAppender">
<url>http://172.17.0.4:9200/_bulk</url>
<index>logs-%date{yyyy-MM-dd}</index>
<type>tester</type>
<properties>
<property>
<name>host</name>
<value>${HOSTNAME}</value>
<allowEmpty>false</allowEmpty>
</property>
<property>
<name>severity</name>
<value>%level</value>
</property>
<property>
<name>thread</name>
<value>%thread</value>
</property>
<property>
<name>stacktrace</name>
<value>%ex</value>
</property>
<property>
<name>logger</name>
<value>%logger</value>
</property>
</properties>
<headers>
<header>
<name>Content-Type</name>
<value>text/plain</value>
</header>
</headers> …
```
> JAMES-2022 Add ES logback appender as a guice-cassandra dependency

- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageDAOTest.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMailboxManager.java
The mailboxId creation can be skept during mapper execution and swallowed, leading in an empty collection.
Here is the code giving more context:
```
locker.executeWithLock(mailboxSession, mailbox, new LockAwareExecution<Void>() {
public Void execute() throws MailboxException {
if (!mailboxExists(mailbox, mailboxSession)) {
final org.apache.james.mailbox.store.mail.model.Mailbox m = doCreateMailbox(mailbox, mailboxSession);
final MailboxMapper mapper = mailboxSessionMapperFactory.getMailboxMapper(mailboxSession);
mapper.execute(new TransactionalMapper.VoidTransaction() {
public void runVoid() throws MailboxException {
mailboxIds.add(mapper.save(m));
}
});
// notify listeners
dispatcher.mailboxAdded(mailboxSession, m);
}
return null;
}
}, true);
```
This "skipping mailboxes at the last …
> JAMES-2047 Fix unstable test

- mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMessageIdManager.java
- server/protocols/jmap/src/main/java/org/apache/james/jmap/methods/SetMessagesUpdateProcessor.java
- server/protocols/jmap/src/main/java/org/apache/james/jmap/model/UpdateMessagePatch.java
- server/protocols/jmap/src/test/java/org/apache/james/jmap/model/UpdateMessagePatchTest.java
Why is it needed?
Issue details:
I was surprised to realise how SetInMailboxes operation is slow. See the attached screenshots for rationals. It was generated while sorting 2 weeks of email. Thus, I had an optimisation round on my free time. I found:
-  That we can avoid a read in StoreMessageIdManager by avoiding calling delete (which comes at the cost of extra reads).
-  We can avoid updating flags when none specified
The last point implies:
-  Avoiding extra reads before updating flags
-  Avoiding noop updates of search engine
-  This noop updates is, in fact, a replace with current flags, which can compete with parallel flags updates. Thus, this optimisation also improve concurrent behaviours, by uncoupling SetFlags and SetInMailboxes
> JAMES-2098 Some SetInMailboxes optimization on my free time

- backends-common/cassandra/src/test/java/org/apache/james/backends/cassandra/DockerCassandraRule.java
- mailbox/api/src/main/java/org/apache/james/mailbox/model/AttachmentId.java
- mailbox/api/src/test/java/org/apache/james/mailbox/model/AttachmentIdTest.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/CassandraMailboxSessionMapperFactory.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraAttachmentDAO.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraAttachmentDAOV2.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraAttachmentMapper.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraBlobsDAO.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageDAO.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageIdMapper.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/modules/CassandraAttachmentModule.java
- mailbox/cassandra/src/main/java/org/apache/james/mailbox/cassandra/table/CassandraAttachmentV2Table.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/CassandraMailboxManagerProvider.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/CassandraSubscriptionManagerTest.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/CassandraTestSystemFixture.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/TestCassandraMailboxSessionMapperFactory.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraAttachmentDAOTest.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraAttachmentDAOV2Test.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraAttachmentFallbackTest.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraAttachmentFallbackTestTest.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraBlobsDAOTest.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraMailboxManagerAttachmentTest.java
- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraMapperProvider.java
- mpt/impl/imap-mailbox/cassandra/pom.xml
- mpt/impl/imap-mailbox/cassandra/src/test/java/org/apache/james/mpt/imapmailbox/cassandra/host/CassandraHostSystem.java
- server/container/util-java8/src/main/java/org/apache/james/util/FluentFutureStream.java
- server/container/util-java8/src/test/java/org/apache/james/util/FluentFutureStreamTest.java
Includes also:
- FluentFutureStream::collect (more convenient, less boiler plate in business classes)
- Easy instantiation of the CassandraMessageMapperFactory for tests: limit argument hell, and makes writing tests from this simple. I don't want to keep changing specific tests every time we add a DAO.
> MAILBOX-304 Store attachment payload as BlobId

- backends-common/cassandra/src/test/java/org/apache/james/backends/cassandra/DockerCassandraRule.java
This reverts commit 2c411e8b5bb8d304f5b2775f0e28e83e9ccf9859.
> Revert "JAMES-2133 Avoid cassandra test containers to cluster together"

- mailbox/maildir/src/main/java/org/apache/james/mailbox/maildir/mail/MaildirMessageMapper.java
- mailbox/maildir/src/main/java/org/apache/james/mailbox/maildir/mail/model/MaildirMessage.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/model/FlagsFactory.java
- mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/model/impl/SimpleMailboxMessage.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/FlagsFactoryTest.java
- We need a non null MessageId
- User flags can be null, FlagsFactory need to support it
- Attachment copy is not supported
I'll add the maildir profile in a separate PR (PRO TIP: limit build isolation problems ;-))
> PROTOCOLS-117 General fixes: Fix MAILDIR MPT tests

- core/src/main/java/org/apache/james/core/User.java
- core/src/test/java/org/apache/james/core/UserTest.java
Because user/domain parsing is required several time in recent PRs:
- When checking mailbox shares belongs to the same domain ( https://github.com/linagora/james-project/pull/1091 )
- When handling path conversion logic ( https://github.com/linagora/james-project/pull/1087 )
- When ensuring characters are disabled in local parts (yet to come!)
Thus we should have:
- A core object for this (maibox and server-data. As far as I know, we don't want hard dependency between them)
- And it should just be a parsing utility.
> PROTOCOLS-117 Introduce a generic class for user/domain parsing

- mpt/pom.xml
- pom.xml
- server/protocols/jmap-integration-testing/jmap-integration-testing-common/src/test/java/org/apache/james/jmap/methods/integration/cucumber/DownloadStepdefs.java
- server/protocols/jmap-integration-testing/jmap-integration-testing-common/src/test/java/org/apache/james/jmap/methods/integration/cucumber/UploadStepdefs.java
- server/protocols/jmap-integration-testing/jmap-integration-testing-common/src/test/resources/cucumber/GetMessages.feature
The following libraries were reported by the OWASP Dependency Checker as containing CVEs:
- ActiveMQ (CVE-2015-5183 and CVE-2015-5184)
-> upgrade from 5.15.0 to 5.15.2 (last stable)
- logback-classic (CVE-2017-5929)
-> upgrade from 1.1.7 to 1.1.11 (last stable of 1.1.x)
- jetty (CVE-2017-9735)
-> upgrade from 9.4.4 to 9.4.7.v20170914 (last stable)
> JAMES-2209 Upgrade libraries containing CVEs

- mailet/base/src/test/java/org/apache/mailet/base/test/MimeMessageBuilder.java
- mailet/standard/src/main/java/org/apache/james/transport/mailets/ContactExtractor.java
- mailet/standard/src/test/java/org/apache/james/transport/mailets/ContactExtractorTest.java
- server/container/util-java8/src/main/java/org/apache/james/util/StreamUtils.java
- server/container/util-java8/src/test/java/org/apache/james/util/StreamUtilsTest.java
Finally I did not use Mime4j because Mime4j is not very good to extract the name of the recipients.
It can be done with some ugly casting, but then it would be better to differentiate name from address in the collected contacts API, because Mime4j don't give back the name exactly like it has been parsed.
> JAMES-2235 Contact Extractor should accept non stritly parsable recipients

- pom.xml
- server/data/data-ldap-integration-testing/src/test/java/org/apache/james/user/ldap/ReadOnlyUsersLDAPRepositoryTest.java
- server/data/data-ldap/pom.xml
- server/data/data-ldap/src/main/java/org/apache/james/user/ldap/ReadOnlyUsersLDAPRepository.java
The user-controlled "name" input is not sanitized when making LDAP searches with searchAndBuildUser(). This could lead to LDAP injections using special characters.
> JAMES-2243 Encode special characters in LDAP search filter

- server/protocols/jmap/src/main/java/org/apache/james/jmap/model/mailbox/Rights.java
Each mailbox acl contains a special `owner` entry.
Thus, having that special entry is expected.
As JMAP layer right resolution don't support `special` right entry, these special entries are logged as unexpected. What they are not.
It leads to overkill logging.
We should keep filtering out special `owner` entry, but should not log it.
> JAMES-2247 Don't log owner ACL entry as unexpected

- server/protocols/protocols-smtp/src/main/java/org/apache/james/smtpserver/netty/SMTPChannelUpstreamHandler.java
Unit testing for https://github.com/apache/james-project/pull/83
JIRA issue is https://issues.apache.org/jira/browse/JAMES-2217
I guess we can fix commit prefix at merge time.
> Issue in smtp channel upstream handler

- pom.xml
Using Guava 18.0, Datastax prints a log message saying it uses a compatibility layer :
```
14:22:22.707 [INFO ] c.d.d.c.GuavaCompatibility - Detected Guava < 19 in the classpath, using legacy compatibility layer
```
Using guava 19.0, this message is no more printed
> Upgrade Guava to 19.0

- protocols/imap/src/main/java/org/apache/james/imap/processor/AppendProcessor.java
Testing for https://github.com/apache/james-project/pull/79
Consuming bytes individually can be inefficient if the input stream is
not buffered. IOUtils.copy() buffers the input internally, so there is
no need to use a BufferedInputStream.
> Consume by copying to NULL_OUTPUT_STREAM

- server/mailet/mailets/src/main/java/org/apache/james/transport/util/SizeUtils.java
Depending on the host system, you could end up with a `,` or a `.`, leading to test failures.
Both of them being acceptable results, I propose to use a REGEX for accepting both.
> JAMES-2237 Size related tests were platform dependant

- pom.xml
- server/protocols/webadmin/webadmin-core/src/test/java/org/apache/james/webadmin/WebAdminUtils.java
- server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/routes/DomainQuotaRoutesTest.java
- server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/routes/ElasticSearchQuotaSearchExtension.java
- server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/routes/GlobalQuotaRoutesTest.java
- server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/routes/ScanningQuotaSearchExtension.java
- server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/routes/UserQuotaRoutesTest.java
- server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/routes/WebAdminQuotaSearchTestSystem.java
This reverts commit f8faf50e8cb76cdd1931ddcebb0f3e4865028eaf.
This commit introduced a move toward JUNIT 5.2.0 in order to use programmatically registered extensions, which looked very promissing.
However, JUNIT 5.2.0 is not stable yet, and that lead to many tests being skept. As such, we failed finding a satisfying solution, so we have to revert, in order to get all tests played.
> Revert "JAMES-2404 Use programmatically registered extensions"

- mailbox/cassandra/src/test/java/org/apache/james/mailbox/cassandra/mail/CassandraMailboxMapperConcurrencyTest.java
- mailbox/plugin/quota-mailing/src/test/java/org/apache/james/mailbox/quota/mailing/listeners/QuotaThresholdMailingIntegrationTest.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/MessageIdMapperTest.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/mail/model/MessageMapperTest.java
- mailbox/tika/src/test/java/org/apache/james/mailbox/tika/CachingTextExtractorTest.java
- protocols/imap/src/test/java/org/apache/james/imap/processor/base/UidMsnConverterTest.java
- protocols/smtp/src/test/java/org/apache/james/protocols/smtp/AbstractSMTPServerTest.java
- server/container/guice/guice-common/src/test/java/org/apache/james/utils/InMemoryMailRepositoryStoreTest.java
- server/container/util/src/main/java/org/apache/james/util/concurrency/ConcurrentTestRunner.java
- server/container/util/src/test/java/org/apache/james/util/concurrency/ConcurrentTestRunnerTest.java
- server/data/data-api/src/test/java/org/apache/james/mailrepository/api/MailRepositoryUrlStoreContract.java
- server/mailrepository/mailrepository-api/src/test/java/org/apache/james/mailrepository/MailRepositoryContract.java
- server/protocols/jmap-integration-testing/jmap-integration-testing-common/src/test/java/org/apache/james/jmap/ProvisioningTest.java
- server/protocols/jmap/src/test/java/org/apache/james/jmap/DefaultMailboxesProvisioningFilterTest.java
This allows:
- Removing the confusion between threadCount & operationCount
- Allow a default value for operationCount (1)
> JAMES-2464 ConcurrentTestRunner should use a builder

- server/mailet/integration-testing/src/test/java/org/apache/james/transport/mailets/SpamAssassinTest.java
No feedback is tested there hence SPamAssassin container is stateless.
Gain of 30s on that test
> JAMES-2470 SpamAssassin can be static in mailet integration tests

- server/protocols/jmap-integration-testing/cassandra-jmap-integration-testing/src/test/java/org/apache/james/jmap/cassandra/cucumber/CassandraDownloadCucumberTest.java
- server/protocols/jmap-integration-testing/cassandra-jmap-integration-testing/src/test/java/org/apache/james/jmap/cassandra/cucumber/CassandraMailboxSharingTest.java
- server/protocols/jmap-integration-testing/cassandra-jmap-integration-testing/src/test/java/org/apache/james/jmap/cassandra/cucumber/CassandraMessageSharingTest.java
- server/protocols/jmap-integration-testing/cassandra-jmap-integration-testing/src/test/java/org/apache/james/jmap/cassandra/cucumber/CassandraUploadCucumberTest.java
- server/protocols/jmap-integration-testing/memory-jmap-integration-testing/src/test/java/org/apache/james/jmap/memory/cucumber/MemoryDownloadCucumberTest.java
- server/protocols/jmap-integration-testing/memory-jmap-integration-testing/src/test/java/org/apache/james/jmap/memory/cucumber/MemorySharingTest.java
- server/protocols/jmap-integration-testing/memory-jmap-integration-testing/src/test/java/org/apache/james/jmap/memory/cucumber/MemoryUploadCucumberTest.java
- server/queue/queue-api/src/test/java/org/apache/james/queue/api/MailQueueMetricContract.java
- server/queue/queue-jms/src/test/java/org/apache/james/queue/jms/JMSMailQueueTest.java
WARNING: Found tags option '\~@Ignore'. Support for '~@tag' will be removed from the next release of Cucumber-JVM. Please use 'not @tag' instead.
> JAMES-2487 Remove deprecation warning

- server/protocols/webadmin/webadmin-core/src/main/java/org/apache/james/webadmin/WebAdminServer.java
- server/protocols/webadmin/webadmin-core/src/test/java/org/apache/james/webadmin/routes/ErrorRoutesTest.java
This strategy is better than using a static setUp/tearDown. It is enabled thanks to latest Spark upgrade.
> JAMES-2314 Use awaitStop to await error handlers cleanup

- mailbox/api/src/test/java/org/apache/james/mailbox/MailboxManagerTest.java
- mailet/base/src/test/java/org/apache/mailet/base/MailetPipelineLoggingTest.java
- pom.xml
- server/container/guice/cassandra-guice/src/test/java/org/apache/james/JamesServerWithRetryConnectionTest.java
- server/container/metrics/metrics-es-reporter/pom.xml
- server/container/metrics/metrics-es-reporter/src/main/java/org/apache/james/metrics/es/ESMetricReporter.java
- server/container/metrics/metrics-es-reporter/src/test/java/org/apache/james/metric/es/DockerElasticSearch2Extension.java
- server/container/metrics/metrics-es-reporter/src/test/java/org/apache/james/metric/es/DockerElasticSearch6Extension.java
- server/container/metrics/metrics-es-reporter/src/test/java/org/apache/james/metric/es/ES2ReporterTest.java
- server/container/metrics/metrics-es-reporter/src/test/java/org/apache/james/metric/es/ES6ReporterTest.java
- server/container/metrics/metrics-es-reporter/src/test/java/org/apache/james/metric/es/ESReportedConfigurationTest.java
- server/container/metrics/metrics-es-reporter/src/test/java/org/apache/james/metric/es/ESReporterContract.java
- server/container/metrics/metrics-es-reporter/src/test/java/org/apache/james/metric/es/ESReporterTest.java
- server/data/data-ldap/src/test/java/org/apache/james/user/ldap/ReadOnlyUsersLDAPRepositoryTest.java
- server/protocols/jmap/src/test/java/org/apache/james/jmap/model/KeywordsTest.java
- third-party/spamassassin/src/test/java/org/apache/james/spamassassin/SpamAssassinExtension.java
Here is a new PR to make James metrics compatible with Elastic Search 6.
This time I handled integration tests, and also externalized the needed library. This library needs to be released and the version needs to be updated so that we can merge this PR.
Replaces #1981
> James 2617 es6 metrics 2

- dockerfiles/run/guice/cassandra-ldap/Dockerfile
- dockerfiles/run/guice/cassandra-rabbitmq-ldap/Dockerfile
- dockerfiles/run/guice/cassandra-rabbitmq/Dockerfile
- dockerfiles/run/guice/cassandra/Dockerfile
- dockerfiles/run/guice/jpa-smtp/Dockerfile
- dockerfiles/run/guice/jpa/Dockerfile
- dockerfiles/run/spring/Dockerfile
**Original with JDK**
✗ docker image inspect linagora/james-project:latest | gron | grep -i size
json[0].Size = 741657808;
json[0].VirtualSize = 741657808;
Compressed Size in DockerHub: 351 MB
**With JRE**
✗ docker image inspect james_run | gron | grep -i size                    
json[0].Size = 566924448;
json[0].VirtualSize = 566924448;
Compressed Size in DockerHub: 294 MB
**With JRE-alpine**
✗ docker image inspect james_run | gron | grep -i size
json[0].Size = 207138815;
json[0].VirtualSize = 207138815;
Compressed Size in DockerHub: 168 MB
> JAMES-2622 Use an optimized JRE based image in dockerfiles

- server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/Dequeuer.java
- server/queue/queue-rabbitmq/src/test/java/org/apache/james/queue/rabbitmq/RabbitMQMailQueueTest.java
Found the malicious commit introducing the issue :
```
[ERROR]   ForwardSmtpTest.forwardingAnEmailShouldWork:79 » ConditionTimeout Assertion co...
```
Reverted it. Let's see if it goes green !
> Revert "JAMES-2733 RabbitMQ should not dequeue deleted elements"

- server/testing/src/main/java/org/apache/james/utils/IMAPMessageReader.java
Let's see what the CI think about it
> IMAPMessageReader should disconnect when closed, not launch t IMAP CLOSE command

- server/container/guice/mailet/src/main/java/org/apache/james/modules/server/CamelMailetContainerModule.java
- server/mailet/mailetcontainer-camel/src/main/java/org/apache/james/mailetcontainer/impl/JamesMailetContext.java
- server/mailet/mailetcontainer-camel/src/test/java/org/apache/james/mailetcontainer/impl/JamesMailetContextTest.java
Reusing a maybe not yet initialized component is dangerous. We should
rather do this as a startable to ensure initialization is well performed
Additionally, JamesMailetContext should rely of constructor based injected
final fields where possible.
Encoutered issue in Deployment tests:
```
Exception in thread "main" com.google.inject.ProvisionException: Unable to provision, see the following errors:
1) Error in custom provider, feign.RetryableException: No route to host (Host unreachable) executing GET http://rabbitmq:15672/api/queues
at org.apache.james.modules.server.CamelMailetContainerModule.provideMailetContext(CamelMailetContainerModule.java:69) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> …
```
> JAMES-1902 Avoid creating the SPOOL MailQueue upon injection

- server/blob/blob-api/src/main/java/org/apache/james/blob/api/Store.java
RabbitMQ tests got a 0.5% failure rate:
```
[21312fd7e0e3ffaf3f478f2e168b0c21ffaf5ecc] [ERROR] increasingBucketCountShouldAllowBrowsingAllQueueElements{CassandraCluster}  Time elapsed: 0.274 s  <<< ERROR!
[21312fd7e0e3ffaf3f478f2e168b0c21ffaf5ecc] java.lang.IllegalStateException: block()/blockFirst()/blockLast() are blocking, which is not supported in thread parallel-2
```
> JAMES-2630 Use an elastic scheduler for byte reading

- backends-common/elasticsearch/src/test/java/org/apache/james/backends/es/DockerElasticSearch.java
- backends-common/elasticsearch/src/test/java/org/apache/james/backends/es/DockerElasticSearchRule.java
- mailbox/plugin/quota-search-elasticsearch/src/test/java/org/apache/james/quota/search/elasticsearch/ElasticSearchQuotaSearchTestSystemExtension.java
- mpt/impl/imap-mailbox/elasticsearch/src/test/java/org/apache/james/mpt/imapmailbox/elasticsearch/host/ElasticSearchHostSystem.java
- server/container/guice/cassandra-guice/src/test/java/org/apache/james/DockerElasticSearchExtension.java
- server/container/guice/cassandra-guice/src/test/java/org/apache/james/DockerElasticSearchRule.java
- server/container/metrics/metrics-es-reporter/src/test/java/org/apache/james/metric/es/DockerElasticSearchExtension.java
- server/protocols/jmap-integration-testing/cassandra-jmap-integration-testing/src/test/java/org/apache/james/jmap/cassandra/cucumber/CassandraStepdefs.java
- server/protocols/jmap-integration-testing/rabbitmq-jmap-integration-testing/src/test/java/org/apache/james/jmap/rabbitmq/cucumber/awss3/RabbitMQAwsS3Stepdefs.java
- server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/routes/ElasticSearchQuotaSearchExtension.java
Throw a IllegalStateException when flush fails and be honest
about the fact we flush indices (and nothing in elasticsearch doc
says that it make anything more synchronous)
Also throw IllegalStateException when cleanup fails
> Improve ES container methods semantic

- server/blob/blob-api/src/main/java/org/apache/james/blob/api/BlobStore.java
- server/blob/blob-api/src/main/java/org/apache/james/blob/api/MetricableBlobStore.java
- server/blob/blob-api/src/test/java/org/apache/james/blob/api/BucketBlobStoreContract.java
- server/blob/blob-api/src/test/java/org/apache/james/blob/api/MetricableBlobStoreContract.java
- server/blob/blob-cassandra/src/main/java/org/apache/james/blob/cassandra/CassandraBlobsDAO.java
- server/blob/blob-cassandra/src/test/java/org/apache/james/blob/cassandra/CassandraBlobsDAOTest.java
- server/blob/blob-memory/src/main/java/org/apache/james/blob/memory/MemoryBlobStore.java
- server/blob/blob-memory/src/test/java/org/apache/james/blob/memory/MemoryBlobStoreTest.java
- server/blob/blob-objectstorage/src/main/java/org/apache/james/blob/objectstorage/ObjectStorageBlobsDAO.java
- server/blob/blob-objectstorage/src/test/java/org/apache/james/blob/objectstorage/ObjectStorageBlobsDAOTest.java
- server/blob/blob-union/src/main/java/org/apache/james/blob/union/UnionBlobStore.java
- server/blob/blob-union/src/test/java/org/apache/james/blob/union/UnionBlobStoreTest.java
I feel like I cannot test in the contract if the bucket creation was a success or not... Do I need? Should we add then a `getBucket` API in BlobStore? Or should I return a `Bucket` after creation (which might require the interface to be created) ?
> JAMES-2806 bucket memory implementation for BlobStore + contract

- backends-common/cassandra/src/test/java/org/apache/james/backends/cassandra/DockerCassandra.java
Only 200mo where allocated to
/var/lib/cassandra
Some repeated tests failed after some time because the volume was full.
With the logs we could see that the limited space prevented the compaction to run hence the crash after some time
> JAMES-2880 disable auto_snapshot for cassandra in tests

- mailbox/elasticsearch/src/main/java/org/apache/james/mailbox/elasticsearch/json/HeaderCollection.java
- mailbox/elasticsearch/src/test/java/org/apache/james/mailbox/elasticsearch/json/HeaderCollectionTest.java
- mailbox/scanning-search/src/test/java/org/apache/james/mailbox/store/search/SimpleMessageSearchIndexTest.java
- mailbox/store/src/test/java/org/apache/james/mailbox/store/search/AbstractMessageSearchIndexTest.java
It seems that from ES 5.0, dots are permitted again in fields names : https://www.elastic.co/guide/en/elasticsearch/reference/2.4/dots-in-names.html
> JAMES-2241 can reindex header fields with dots after upgrading to ES6

- pom.xml
ESReporter, due to the previous 0-dependency approach, relied on HTTPUrl java lib.
Due to that choice, some dark magic wizardry well-deserving a latin quota, **we are leaking a thread+connection everytime we do a reporting**.
The **no-deps** choice is no longer justify today thus we should port the transport layer of ESReporter to a modern HTTP framework.
use the work done in https://github.com/linagora/elasticsearch-metrics-reporter-java/pull/8
> JAMES-2966 bump elastic metrics reporter version to avoid thread leaks

- backends-common/rabbitmq/src/main/java/org/apache/james/backends/rabbitmq/ReactorRabbitMQChannelPool.java
- backends-common/rabbitmq/src/test/java/org/apache/james/backends/rabbitmq/RabbitMQHealthCheckTest.java
- server/protocols/webadmin-integration-test/src/test/java/org/apache/james/webadmin/integration/WebAdminServerIntegrationTest.java
Channel was not given back to the pool, causing repeated calling of this
endpoint to fail
> JAMES-2937 Calling several time the RabbitMQ endpoint should not fail

- grafana-reporting/Cassandra_driver-1504068385404-dashboard.json
- grafana-reporting/IMAP_board-1488774825351-dashboard.json
- grafana-reporting/IMAP_count_board-1488774815587-dashboard.json
- grafana-reporting/JAMES_DNS_dashboard-1491268903944-dashboard.json
- grafana-reporting/JMAP_board-1488774804236-dashboard.json
- grafana-reporting/JMAP_count_board-1488774795514-dashboard.json
- grafana-reporting/James_JVM-1504068360629-dashboard.json
- grafana-reporting/MAILET-1490071694187-dashboard.json
- grafana-reporting/MATCHER-1490071813409-dashboard.json
- grafana-reporting/MailQueue-1490071879988-dashboard.json
- grafana-reporting/MailboxListeners rate-1552903378376.json
- grafana-reporting/MailboxListeners-1528958667486-dashboard.json
- grafana-reporting/Miscalleneous-1490072265151-dashboard.json
- grafana-reporting/PreDeletionHooks-1553684324244-dashboard.json
- grafana-reporting/SMTP_board-1488774774172-dashboard.json
- grafana-reporting/SMTP_count_board-1488774761350-dashboard.json
- grafana-reporting/SpamAssassin-1522226824255-dashboard.json
- grafana-reporting/Tika-1522226794419-dashboard.json
Quotes query to avoid all the panel of a board using queries containing the same prefix followed by an `-` to display the same values.
Plus fix the IMAP CREATE metric reporting
> Fix grafana boards

- server/container/guice/cassandra-guice/src/main/java/org/apache/james/CassandraJamesServerMain.java
- server/container/guice/cassandra-ldap-guice/src/main/java/org/apache/james/CassandraLdapJamesServerMain.java
- server/container/guice/cassandra-rabbitmq-guice/src/main/java/org/apache/james/CassandraRabbitMQJamesServerMain.java
- server/container/guice/guice-common/src/main/java/org/apache/james/JamesServerMain.java
- server/container/guice/jpa-guice/src/main/java/org/apache/james/JPAJamesServerMain.java
- server/container/guice/jpa-smtp-common/src/main/java/org/apache/james/JPAJamesServerMain.java
- server/container/guice/memory-guice/src/main/java/org/apache/james/MemoryJamesServerMain.java
James should not shut down immediatly on SIGTERM, but it gracefully terminates connections.
In a kubernetes context for instance:
```
It might take some time before a component such as kube-proxy or the Ingress controller is notified of the endpoint changes.
Hence, traffic might still flow to the Pod despite it being marked as terminated.
The app should stop accepting new requests on all remaining connections, and close these once the outgoing queue is drained.
If you need a refresher on how endpoints are propagated in your cluster, read this article on how to handle client requests properly.
```
(Source: https://learnk8s.io/production-best-practices)
I think it also makes sens out of this context.
A graceful shutdown furthermore decrease the risk of inconsistencies in the underlying …
>  JAMES-3108 Stop james server upon graceful shutdown

- protocols/imap/src/main/java/org/apache/james/imap/processor/AbstractMailboxProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/AbstractSelectionProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/AppendProcessor.java
- protocols/imap/src/main/java/org/apache/james/imap/processor/base/SelectedMailboxImpl.java
- protocols/imap/src/test/java/org/apache/james/imap/processor/base/MailboxEventAnalyserTest.java
- protocols/imap/src/test/java/org/apache/james/imap/processor/base/SelectedMailboxImplTest.java
Using glowroot, a huge amount of time is used getting mailbox information
count   time     Query
2,128	 12,604.5 SELECT FROM acl WHERE id=:id;
2,128	  9,120.9 SELECT FROM mailboxPathV2 WHERE namespace=:nam.
2,128	  5,873.4 SELECT id,mailboxbase,uidvalidity,name FROM mailbox WHERE id=:id;
1,063	  5,653.2 UPDATE modseq SET nextModseq=:nextModseq WHERE mailboxId=:mailboxId IF nextModseq=:...
This changeset allow dividing by 2 the reads on mailbox potentially saving
many useless Cassandra queries.
According to glowroot, **this should result in a 14.5% Cassandra query time decrease.**
> [Performance] Enhance AppendProcessor performances

- server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/service/MailboxesExportRequestToTaskTest.java
Task completion cannot be expected to be instantaneous.
> JAMES-3072 Await task completion in Mailbox Export webAdmin tests

- mailbox/store/src/main/java/org/apache/james/mailbox/store/search/MessageSearches.java
The date format used to compare the date in order to sort them, used 'hh' in the date format to represent the hour instead of 'kk'.
https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html
So one date in the afternoon could not be compared with a date in the morning.
This leads to error in the memory implementation. And some flacky test passing at certain hours but not others...
> JAMES-3380 use non am/pm dependent hour format

- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/EmailQueryMethodContract.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/json/EmailQuerySerializer.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/EmailQuery.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/EmailQueryMethod.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/model/Invocation.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/utils/search/MailboxFilter.scala
Managing in this PR:
* collapseThreads param does noop
* use of `allInThreadHaveKeyword` and `someInThreadHaveKeyword` in sort generates an `unsuportedSort` error method 
* use of `allInThreadHaveKeyword`, `someInThreadHaveKeyword` and `noneInThreadHaveKeyword` in filter generates an `unsupportedFilter` error method
* Anchor/AnchorOffset are not supported as request params
Remaining:
* Unknown filter should return an error => in an other PR, it sounds quite tricky with the current code, and it's not part of this task initially
> JAMES-3384 email query unsupported params

- server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/model/JmapMDN.java
- server/protocols/jmap-draft/src/test/java/org/apache/james/jmap/draft/model/JmapMDNTest.java
Missing date headers is misleading, and leads to wrong message ordering, eg in thunderbird.
> JAMES-3402 JMAP MDN messages should have a Date header

- server/container/guice/protocols/jmap/src/main/java/org/apache/james/jmap/rfc8621/RFC8621MethodsModule.java
- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/pom.xml
- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/CustomMethodContract.scala
- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/EventSourceContract.scala
- server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/SessionRoutesContract.scala
- server/protocols/jmap-rfc-8621-integration-tests/memory-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/memory/MemoryEventSourceTest.java
- server/protocols/jmap-rfc-8621/doc/specs/spec/jmap/push.mdown
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/change/StateChange.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/core/JmapRfc8621Configuration.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/core/WebSocketTransport.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/json/ResponseSerializer.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/routes/EventSourceRoutes.scala
- server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/routes/WebSocketRoutes.scala
- server/protocols/jmap-rfc-8621/src/test/scala/org/apache/james/jmap/change/StateChangeListenerTest.scala
- server/protocols/jmap-rfc-8621/src/test/scala/org/apache/james/jmap/core/JmapRfc8621ConfigurationTest.scala
- server/protocols/jmap-rfc-8621/src/test/scala/org/apache/james/jmap/routes/SessionRoutesTest.scala
- server/protocols/jmap/src/main/java/org/apache/james/jmap/JMAPUrls.java
- server/protocols/jmap/src/main/java/org/apache/james/jmap/http/Authenticator.java
This reuses the work introduced around WebSocket PUSH
and wraps it around a Server Sent Event transport
layer (over HTTP)
JMAP Spec: https://jmap.io/spec-core.html#event-source
Here is a little read that helped me understand SSE
structure:
https://www.html5rocks.com/en/tutorials/eventsource/basics/
As reactor-netty supports long running HTTP requests but has
no support for SSE by itself, a basic understanding of the
eventStream structure is required.
The current implementation proposal suffer from the following
limitations:
- It does not perform any sanitizing on the ping interval (minimum 1 second) in a perfect world this should likely be configurable as:
- too low values are an ineffective use of the network.
- too high values might exceed some deployments
connection timeout settings …
> JAMES-3457 Implement JMAP PUSH over EventSource
